// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file areas.proto (package ng.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Area, CreateAreaRequest, DeleteAreaRequest, GetAreaRequest, ListAreasRequest, ListAreasResponse, UpdateAreaRequest } from "./areas_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ng.v1.AreaService
 */
export const AreaService = {
  typeName: "ng.v1.AreaService",
  methods: {
    /**
     * @generated from rpc ng.v1.AreaService.Create
     */
    create: {
      name: "Create",
      I: CreateAreaRequest,
      O: Area,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.AreaService.Get
     */
    get: {
      name: "Get",
      I: GetAreaRequest,
      O: Area,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.AreaService.List
     */
    list: {
      name: "List",
      I: ListAreasRequest,
      O: ListAreasResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.AreaService.Update
     */
    update: {
      name: "Update",
      I: UpdateAreaRequest,
      O: Area,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.AreaService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteAreaRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

