// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file areas.proto (package ng.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "./google/api/annotations_pb";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file areas.proto.
 */
export const file_areas: GenFile = /*@__PURE__*/
  fileDesc("CgthcmVhcy5wcm90bxIFbmcudjEiMAoEQXJlYRIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRINCgVjb2xvchgDIAEoCSI6ChFDcmVhdGVBcmVhUmVxdWVzdBIWCgV0aXRsZRgBIAEoCUIHukgEcgIQARINCgVjb2xvchgCIAEoCSIlCg5HZXRBcmVhUmVxdWVzdBITCgJpZBgBIAEoCUIHukgEcgIQASISChBMaXN0QXJlYXNSZXF1ZXN0Ii8KEUxpc3RBcmVhc1Jlc3BvbnNlEhoKBWFyZWFzGAEgAygLMgsubmcudjEuQXJlYSJ/ChFVcGRhdGVBcmVhUmVxdWVzdBITCgJpZBgBIAEoCUIHukgEcgIQARINCgV0aXRsZRgCIAEoCRINCgVjb2xvchgDIAEoCRI3Cgt1cGRhdGVfbWFzaxgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2tCBrpIA8gBASIoChFEZWxldGVBcmVhUmVxdWVzdBITCgJpZBgBIAEoCUIHukgEcgIQATKZAwoLQXJlYVNlcnZpY2USSQoGQ3JlYXRlEhgubmcudjEuQ3JlYXRlQXJlYVJlcXVlc3QaCy5uZy52MS5BcmVhIhiC0+STAhI6ASoiDS9hcGkvdjEvYXJlYXMSRQoDR2V0EhUubmcudjEuR2V0QXJlYVJlcXVlc3QaCy5uZy52MS5BcmVhIhqC0+STAhQSEi9hcGkvdjEvYXJlYXMve2lkfRJQCgRMaXN0EhcubmcudjEuTGlzdEFyZWFzUmVxdWVzdBoYLm5nLnYxLkxpc3RBcmVhc1Jlc3BvbnNlIhWC0+STAg8SDS9hcGkvdjEvYXJlYXMSTgoGVXBkYXRlEhgubmcudjEuVXBkYXRlQXJlYVJlcXVlc3QaCy5uZy52MS5BcmVhIh2C0+STAhc6ASoaEi9hcGkvdjEvYXJlYXMve2lkfRJWCgZEZWxldGUSGC5uZy52MS5EZWxldGVBcmVhUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIagtPkkwIUKhIvYXBpL3YxL2FyZWFzL3tpZH1CKVonZ2l0aHViLmNvbS9saWFtYXdoaXRlL25nL2FwaS9nb2xhbmc7YXBpYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_empty, file_google_protobuf_field_mask, file_buf_validate_validate]);

/**
 * @generated from message ng.v1.Area
 */
export type Area = Message<"ng.v1.Area"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string color = 3;
   */
  color: string;
};

/**
 * Describes the message ng.v1.Area.
 * Use `create(AreaSchema)` to create a new message.
 */
export const AreaSchema: GenMessage<Area> = /*@__PURE__*/
  messageDesc(file_areas, 0);

/**
 * @generated from message ng.v1.CreateAreaRequest
 */
export type CreateAreaRequest = Message<"ng.v1.CreateAreaRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string color = 2;
   */
  color: string;
};

/**
 * Describes the message ng.v1.CreateAreaRequest.
 * Use `create(CreateAreaRequestSchema)` to create a new message.
 */
export const CreateAreaRequestSchema: GenMessage<CreateAreaRequest> = /*@__PURE__*/
  messageDesc(file_areas, 1);

/**
 * @generated from message ng.v1.GetAreaRequest
 */
export type GetAreaRequest = Message<"ng.v1.GetAreaRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message ng.v1.GetAreaRequest.
 * Use `create(GetAreaRequestSchema)` to create a new message.
 */
export const GetAreaRequestSchema: GenMessage<GetAreaRequest> = /*@__PURE__*/
  messageDesc(file_areas, 2);

/**
 * @generated from message ng.v1.ListAreasRequest
 */
export type ListAreasRequest = Message<"ng.v1.ListAreasRequest"> & {
};

/**
 * Describes the message ng.v1.ListAreasRequest.
 * Use `create(ListAreasRequestSchema)` to create a new message.
 */
export const ListAreasRequestSchema: GenMessage<ListAreasRequest> = /*@__PURE__*/
  messageDesc(file_areas, 3);

/**
 * @generated from message ng.v1.ListAreasResponse
 */
export type ListAreasResponse = Message<"ng.v1.ListAreasResponse"> & {
  /**
   * @generated from field: repeated ng.v1.Area areas = 1;
   */
  areas: Area[];
};

/**
 * Describes the message ng.v1.ListAreasResponse.
 * Use `create(ListAreasResponseSchema)` to create a new message.
 */
export const ListAreasResponseSchema: GenMessage<ListAreasResponse> = /*@__PURE__*/
  messageDesc(file_areas, 4);

/**
 * @generated from message ng.v1.UpdateAreaRequest
 */
export type UpdateAreaRequest = Message<"ng.v1.UpdateAreaRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 4;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message ng.v1.UpdateAreaRequest.
 * Use `create(UpdateAreaRequestSchema)` to create a new message.
 */
export const UpdateAreaRequestSchema: GenMessage<UpdateAreaRequest> = /*@__PURE__*/
  messageDesc(file_areas, 5);

/**
 * @generated from message ng.v1.DeleteAreaRequest
 */
export type DeleteAreaRequest = Message<"ng.v1.DeleteAreaRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message ng.v1.DeleteAreaRequest.
 * Use `create(DeleteAreaRequestSchema)` to create a new message.
 */
export const DeleteAreaRequestSchema: GenMessage<DeleteAreaRequest> = /*@__PURE__*/
  messageDesc(file_areas, 6);

/**
 * @generated from service ng.v1.AreaService
 */
export const AreaService: GenService<{
  /**
   * @generated from rpc ng.v1.AreaService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateAreaRequestSchema;
    output: typeof AreaSchema;
  },
  /**
   * @generated from rpc ng.v1.AreaService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetAreaRequestSchema;
    output: typeof AreaSchema;
  },
  /**
   * @generated from rpc ng.v1.AreaService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListAreasRequestSchema;
    output: typeof ListAreasResponseSchema;
  },
  /**
   * @generated from rpc ng.v1.AreaService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateAreaRequestSchema;
    output: typeof AreaSchema;
  },
  /**
   * @generated from rpc ng.v1.AreaService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteAreaRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_areas, 0);

