// Code generated by protograph-gen-ts. DO NOT EDIT.
// source: areas.proto

import { createClient as createGenericClient } from "../../protograph/ts/client.js";

export interface AreaFields {
  id?: Record<string, never>;
  title?: Record<string, never>;
  color?: Record<string, never>;
}

export interface CreateAreaRequestFields {
  title?: Record<string, never>;
  color?: Record<string, never>;
}

export interface GetAreaRequestFields {
  id?: Record<string, never>;
}

export interface ListAreasRequestFields {
}

export interface ListAreasResponseFields {
  areas?: AreaFields;
}

export interface UpdateAreaRequestFields {
  id?: Record<string, never>;
  title?: Record<string, never>;
  color?: Record<string, never>;
  updateMask?: FieldMaskFields;
}

export interface DeleteAreaRequestFields {
  id?: Record<string, never>;
}

export interface AreaResult {
  id?: string;
  title?: string;
  color?: string;
}

export interface CreateAreaRequestResult {
  title?: string;
  color?: string;
}

export interface GetAreaRequestResult {
  id?: string;
}

export interface ListAreasRequestResult {
}

export interface ListAreasResponseResult {
  areas?: AreaResult[];
}

export interface UpdateAreaRequestResult {
  id?: string;
  title?: string;
  color?: string;
  updateMask?: FieldMaskResult;
}

export interface DeleteAreaRequestResult {
  id?: string;
}

export type AreaServiceQuery = {
  create?: {
    $?: Partial<CreateAreaRequestResult>;
  } & AreaFields;
  get?: {
    $?: Partial<GetAreaRequestResult>;
  } & AreaFields;
  list?: {
    $?: Partial<ListAreasRequestResult>;
  } & ListAreasResponseFields;
  update?: {
    $?: Partial<UpdateAreaRequestResult>;
  } & AreaFields;
  delete?: {
    $?: Partial<DeleteAreaRequestResult>;
  } & EmptyFields;
};

export type AreaServiceResult = {
  create?: AreaResult;
  get?: AreaResult;
  list?: ListAreasResponseResult;
  update?: AreaResult;
  delete?: EmptyResult;
};

export type TypedQuery = {
  "ng.v1.AreaService"?: AreaServiceQuery;
};

export type TypedResult = {
  "ng.v1.AreaService"?: AreaServiceResult;
};

/**
 * createClient returns a typed protograph client.
 * @param baseURL Base URL of the backend, e.g. "http://localhost:8080"
 */
export function createClient(baseURL: string) {
  const generic = createGenericClient(baseURL);
  return {
    async fetch(query: TypedQuery): Promise<TypedResult> {
      return generic.fetch(query as Record<string, unknown>) as Promise<TypedResult>;
    },
  };
}
