// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file common.proto (package ng.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SBW5nLnYxKnQKCFByaW9yaXR5EhgKFFBSSU9SSVRZX1VOU1BFQ0lGSUVEEAASDgoKUFJJT1JJVFlfMRABEg4KClBSSU9SSVRZXzIQAhIOCgpQUklPUklUWV8zEAMSDgoKUFJJT1JJVFlfNBAEEg4KClBSSU9SSVRZXzUQBUIpWidnaXRodWIuY29tL2xpYW1hd2hpdGUvbmcvYXBpL2dvbGFuZzthcGliBnByb3RvMw");

/**
 * @generated from enum ng.v1.Priority
 */
export enum Priority {
  /**
   * @generated from enum value: PRIORITY_UNSPECIFIED = 0;
   */
  PRIORITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRIORITY_1 = 1;
   */
  PRIORITY_1 = 1,

  /**
   * @generated from enum value: PRIORITY_2 = 2;
   */
  PRIORITY_2 = 2,

  /**
   * @generated from enum value: PRIORITY_3 = 3;
   */
  PRIORITY_3 = 3,

  /**
   * @generated from enum value: PRIORITY_4 = 4;
   */
  PRIORITY_4 = 4,

  /**
   * @generated from enum value: PRIORITY_5 = 5;
   */
  PRIORITY_5 = 5,
}

/**
 * Describes the enum ng.v1.Priority.
 */
export const PrioritySchema: GenEnum<Priority> = /*@__PURE__*/
  enumDesc(file_common, 0);

