// Code generated by protograph-gen-ts. DO NOT EDIT.
// source: graph.proto

import { createClient as createGenericClient } from "../../protograph/ts/client.js";

export interface EntityFields {
  project?: ProjectFields;
  task?: TaskFields;
  area?: AreaFields;
}

export interface ListRelatedRequestFields {
  id?: Record<string, never>;
  predicate?: Record<string, never>;
  direction?: Record<string, never>;
}

export interface ListRelatedResponseFields {
  entities?: RelatedEntityFields;
}

export interface RelatedEntityFields {
  predicate?: Record<string, never>;
  direction?: Record<string, never>;
  entity?: EntityFields;
}

export interface EntityResult {
  project?: ProjectResult;
  task?: TaskResult;
  area?: AreaResult;
}

export interface ListRelatedRequestResult {
  id?: string;
  predicate?: number;
  direction?: number;
}

export interface ListRelatedResponseResult {
  entities?: RelatedEntityResult[];
}

export interface RelatedEntityResult {
  predicate?: number;
  direction?: number;
  entity?: EntityResult;
}

export type GraphServiceQuery = {
  listRelated?: {
    $?: Partial<ListRelatedRequestResult>;
  } & ListRelatedResponseFields;
};

export type GraphServiceResult = {
  listRelated?: ListRelatedResponseResult;
};

export type TypedQuery = {
  "ng.v1.GraphService"?: GraphServiceQuery;
};

export type TypedResult = {
  "ng.v1.GraphService"?: GraphServiceResult;
};

/**
 * createClient returns a typed protograph client.
 * @param baseURL Base URL of the backend, e.g. "http://localhost:8080"
 */
export function createClient(baseURL: string) {
  const generic = createGenericClient(baseURL);
  return {
    async fetch(query: TypedQuery): Promise<TypedResult> {
      return generic.fetch(query as Record<string, unknown>) as Promise<TypedResult>;
    },
  };
}
