// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file graph.proto (package ng.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "./google/api/annotations_pb";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Area } from "./areas_pb";
import { file_areas } from "./areas_pb";
import type { Project } from "./projects_pb";
import { file_projects } from "./projects_pb";
import type { Task } from "./tasks_pb";
import { file_tasks } from "./tasks_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file graph.proto.
 */
export const file_graph: GenFile = /*@__PURE__*/
  fileDesc("CgtncmFwaC5wcm90bxIFbmcudjEibwoGRW50aXR5EiEKB3Byb2plY3QYASABKAsyDi5uZy52MS5Qcm9qZWN0SAASGwoEdGFzaxgCIAEoCzILLm5nLnYxLlRhc2tIABIbCgRhcmVhGAMgASgLMgsubmcudjEuQXJlYUgAQggKBmVudGl0eSJzChJMaXN0UmVsYXRlZFJlcXVlc3QSEwoCaWQYASABKAlCB7pIBHICEAESIwoJcHJlZGljYXRlGAIgASgOMhAubmcudjEuUHJlZGljYXRlEiMKCWRpcmVjdGlvbhgDIAEoDjIQLm5nLnYxLkRpcmVjdGlvbiI9ChNMaXN0UmVsYXRlZFJlc3BvbnNlEiYKCGVudGl0aWVzGAEgAygLMhQubmcudjEuUmVsYXRlZEVudGl0eSJ4Cg1SZWxhdGVkRW50aXR5EiMKCXByZWRpY2F0ZRgBIAEoDjIQLm5nLnYxLlByZWRpY2F0ZRIjCglkaXJlY3Rpb24YAiABKA4yEC5uZy52MS5EaXJlY3Rpb24SHQoGZW50aXR5GAMgASgLMg0ubmcudjEuRW50aXR5KpkBCglQcmVkaWNhdGUSGQoVUFJFRElDQVRFX1VOU1BFQ0lGSUVEEAASFQoRUFJFRElDQVRFX1BBUlRfT0YQARIVChFQUkVESUNBVEVfSU5fQVJFQRACEhIKDlBSRURJQ0FURV9UQVNLEAMSFQoRUFJFRElDQVRFX1NVQlRBU0sQBBIYChRQUkVESUNBVEVfU1VCUFJPSkVDVBAFKlYKCURpcmVjdGlvbhIZChVESVJFQ1RJT05fVU5TUEVDSUZJRUQQABIWChJESVJFQ1RJT05fT1VUR09JTkcQARIWChJESVJFQ1RJT05fSU5DT01JTkcQAjJ4CgxHcmFwaFNlcnZpY2USaAoLTGlzdFJlbGF0ZWQSGS5uZy52MS5MaXN0UmVsYXRlZFJlcXVlc3QaGi5uZy52MS5MaXN0UmVsYXRlZFJlc3BvbnNlIiKC0+STAhwSGi9hcGkvdjEvZ3JhcGgve2lkfS9yZWxhdGVkQilaJ2dpdGh1Yi5jb20vbGlhbWF3aGl0ZS9uZy9hcGkvZ29sYW5nO2FwaWIGcHJvdG8z", [file_google_api_annotations, file_buf_validate_validate, file_areas, file_projects, file_tasks]);

/**
 * @generated from message ng.v1.Entity
 */
export type Entity = Message<"ng.v1.Entity"> & {
  /**
   * @generated from oneof ng.v1.Entity.entity
   */
  entity: {
    /**
     * @generated from field: ng.v1.Project project = 1;
     */
    value: Project;
    case: "project";
  } | {
    /**
     * @generated from field: ng.v1.Task task = 2;
     */
    value: Task;
    case: "task";
  } | {
    /**
     * @generated from field: ng.v1.Area area = 3;
     */
    value: Area;
    case: "area";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ng.v1.Entity.
 * Use `create(EntitySchema)` to create a new message.
 */
export const EntitySchema: GenMessage<Entity> = /*@__PURE__*/
  messageDesc(file_graph, 0);

/**
 * @generated from message ng.v1.ListRelatedRequest
 */
export type ListRelatedRequest = Message<"ng.v1.ListRelatedRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * UNSPECIFIED = all predicates
   *
   * @generated from field: ng.v1.Predicate predicate = 2;
   */
  predicate: Predicate;

  /**
   * UNSPECIFIED = both directions
   *
   * @generated from field: ng.v1.Direction direction = 3;
   */
  direction: Direction;
};

/**
 * Describes the message ng.v1.ListRelatedRequest.
 * Use `create(ListRelatedRequestSchema)` to create a new message.
 */
export const ListRelatedRequestSchema: GenMessage<ListRelatedRequest> = /*@__PURE__*/
  messageDesc(file_graph, 1);

/**
 * @generated from message ng.v1.ListRelatedResponse
 */
export type ListRelatedResponse = Message<"ng.v1.ListRelatedResponse"> & {
  /**
   * @generated from field: repeated ng.v1.RelatedEntity entities = 1;
   */
  entities: RelatedEntity[];
};

/**
 * Describes the message ng.v1.ListRelatedResponse.
 * Use `create(ListRelatedResponseSchema)` to create a new message.
 */
export const ListRelatedResponseSchema: GenMessage<ListRelatedResponse> = /*@__PURE__*/
  messageDesc(file_graph, 2);

/**
 * @generated from message ng.v1.RelatedEntity
 */
export type RelatedEntity = Message<"ng.v1.RelatedEntity"> & {
  /**
   * the relationship predicate
   *
   * @generated from field: ng.v1.Predicate predicate = 1;
   */
  predicate: Predicate;

  /**
   * which direction the edge runs relative to the queried id
   *
   * @generated from field: ng.v1.Direction direction = 2;
   */
  direction: Direction;

  /**
   * the related entity
   *
   * @generated from field: ng.v1.Entity entity = 3;
   */
  entity?: Entity;
};

/**
 * Describes the message ng.v1.RelatedEntity.
 * Use `create(RelatedEntitySchema)` to create a new message.
 */
export const RelatedEntitySchema: GenMessage<RelatedEntity> = /*@__PURE__*/
  messageDesc(file_graph, 3);

/**
 * @generated from enum ng.v1.Predicate
 */
export enum Predicate {
  /**
   * matches all predicates in ListRelated
   *
   * @generated from enum value: PREDICATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PREDICATE_PART_OF = 1;
   */
  PART_OF = 1,

  /**
   * @generated from enum value: PREDICATE_IN_AREA = 2;
   */
  IN_AREA = 2,

  /**
   * project → task
   *
   * @generated from enum value: PREDICATE_TASK = 3;
   */
  TASK = 3,

  /**
   * task → subtask
   *
   * @generated from enum value: PREDICATE_SUBTASK = 4;
   */
  SUBTASK = 4,

  /**
   * project → subproject
   *
   * @generated from enum value: PREDICATE_SUBPROJECT = 5;
   */
  SUBPROJECT = 5,
}

/**
 * Describes the enum ng.v1.Predicate.
 */
export const PredicateSchema: GenEnum<Predicate> = /*@__PURE__*/
  enumDesc(file_graph, 0);

/**
 * @generated from enum ng.v1.Direction
 */
export enum Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * id is the source of the relationship
   *
   * @generated from enum value: DIRECTION_OUTGOING = 1;
   */
  OUTGOING = 1,

  /**
   * id is the target of the relationship
   *
   * @generated from enum value: DIRECTION_INCOMING = 2;
   */
  INCOMING = 2,
}

/**
 * Describes the enum ng.v1.Direction.
 */
export const DirectionSchema: GenEnum<Direction> = /*@__PURE__*/
  enumDesc(file_graph, 1);

/**
 * @generated from service ng.v1.GraphService
 */
export const GraphService: GenService<{
  /**
   * @generated from rpc ng.v1.GraphService.ListRelated
   */
  listRelated: {
    methodKind: "unary";
    input: typeof ListRelatedRequestSchema;
    output: typeof ListRelatedResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_graph, 0);

