// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file graph.proto (package ng.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListRelatedRequest, ListRelatedResponse } from "./graph_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ng.v1.GraphService
 */
export const GraphService = {
  typeName: "ng.v1.GraphService",
  methods: {
    /**
     * @generated from rpc ng.v1.GraphService.ListRelated
     */
    listRelated: {
      name: "ListRelated",
      I: ListRelatedRequest,
      O: ListRelatedResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

