// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file ng.proto (package ng.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProjectRequest, CreateTaskRequest, DeleteProjectRequest, DeleteTaskRequest, GetProjectRequest, GetTaskRequest, ListProjectsRequest, ListProjectsResponse, ListRelatedRequest, ListRelatedResponse, ListTasksRequest, ListTasksResponse, Project, Task, UpdateProjectRequest, UpdateTaskRequest } from "./ng_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ng.v1.ProjectService
 */
export const ProjectService = {
  typeName: "ng.v1.ProjectService",
  methods: {
    /**
     * @generated from rpc ng.v1.ProjectService.Create
     */
    create: {
      name: "Create",
      I: CreateProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.Get
     */
    get: {
      name: "Get",
      I: GetProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.List
     */
    list: {
      name: "List",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.Update
     */
    update: {
      name: "Update",
      I: UpdateProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteProjectRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service ng.v1.TaskService
 */
export const TaskService = {
  typeName: "ng.v1.TaskService",
  methods: {
    /**
     * @generated from rpc ng.v1.TaskService.Create
     */
    create: {
      name: "Create",
      I: CreateTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.Get
     */
    get: {
      name: "Get",
      I: GetTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.List
     */
    list: {
      name: "List",
      I: ListTasksRequest,
      O: ListTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.Update
     */
    update: {
      name: "Update",
      I: UpdateTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteTaskRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service ng.v1.GraphService
 */
export const GraphService = {
  typeName: "ng.v1.GraphService",
  methods: {
    /**
     * @generated from rpc ng.v1.GraphService.ListRelated
     */
    listRelated: {
      name: "ListRelated",
      I: ListRelatedRequest,
      O: ListRelatedResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

