// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file projects.proto (package ng.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProjectRequest, DeleteProjectRequest, GetProjectRequest, ListProjectsRequest, ListProjectsResponse, Project, UpdateProjectRequest } from "./projects_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ng.v1.ProjectService
 */
export const ProjectService = {
  typeName: "ng.v1.ProjectService",
  methods: {
    /**
     * @generated from rpc ng.v1.ProjectService.Create
     */
    create: {
      name: "Create",
      I: CreateProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.Get
     */
    get: {
      name: "Get",
      I: GetProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.List
     */
    list: {
      name: "List",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.Update
     */
    update: {
      name: "Update",
      I: UpdateProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.ProjectService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteProjectRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

