// Code generated by protograph-gen-ts. DO NOT EDIT.
// source: projects.proto

import { createClient as createGenericClient } from "../../protograph/ts/client.js";

export interface ProjectFields {
  id?: Record<string, never>;
  title?: Record<string, never>;
  content?: Record<string, never>;
  parentId?: Record<string, never>;
  status?: Record<string, never>;
  areaId?: Record<string, never>;
  projects?: ProjectFields;
}

export interface CreateProjectRequestFields {
  title?: Record<string, never>;
  content?: Record<string, never>;
  parentId?: Record<string, never>;
  status?: Record<string, never>;
  areaId?: Record<string, never>;
}

export interface GetProjectRequestFields {
  id?: Record<string, never>;
}

export interface ListProjectsRequestFields {
  parentId?: Record<string, never>;
  status?: Record<string, never>;
  areaId?: Record<string, never>;
}

export interface ListProjectsResponseFields {
  projects?: ProjectFields;
}

export interface UpdateProjectRequestFields {
  id?: Record<string, never>;
  title?: Record<string, never>;
  content?: Record<string, never>;
  parentId?: Record<string, never>;
  status?: Record<string, never>;
  areaId?: Record<string, never>;
}

export interface DeleteProjectRequestFields {
  id?: Record<string, never>;
}

export interface ProjectResult {
  id?: string;
  title?: string;
  content?: string;
  parentId?: string;
  status?: number;
  areaId?: string;
  projects?: ProjectResult[];
}

export interface CreateProjectRequestResult {
  title?: string;
  content?: string;
  parentId?: string;
  status?: number;
  areaId?: string;
}

export interface GetProjectRequestResult {
  id?: string;
}

export interface ListProjectsRequestResult {
  parentId?: string;
  status?: number;
  areaId?: string;
}

export interface ListProjectsResponseResult {
  projects?: ProjectResult[];
}

export interface UpdateProjectRequestResult {
  id?: string;
  title?: string;
  content?: string;
  parentId?: string;
  status?: number;
  areaId?: string;
}

export interface DeleteProjectRequestResult {
  id?: string;
}

export type ProjectServiceQuery = {
  create?: {
    $?: Partial<CreateProjectRequestResult>;
  } & ProjectFields;
  get?: {
    $?: Partial<GetProjectRequestResult>;
  } & ProjectFields;
  list?: {
    $?: Partial<ListProjectsRequestResult>;
  } & ListProjectsResponseFields;
  update?: {
    $?: Partial<UpdateProjectRequestResult>;
  } & ProjectFields;
  delete?: {
    $?: Partial<DeleteProjectRequestResult>;
  } & EmptyFields;
};

export type ProjectServiceResult = {
  create?: ProjectResult;
  get?: ProjectResult;
  list?: ListProjectsResponseResult;
  update?: ProjectResult;
  delete?: EmptyResult;
};

export type TypedQuery = {
  "ng.v1.ProjectService"?: ProjectServiceQuery;
};

export type TypedResult = {
  "ng.v1.ProjectService"?: ProjectServiceResult;
};

/**
 * createClient returns a typed protograph client.
 * @param baseURL Base URL of the backend, e.g. "http://localhost:8080"
 */
export function createClient(baseURL: string) {
  const generic = createGenericClient(baseURL);
  return {
    async fetch(query: TypedQuery): Promise<TypedResult> {
      return generic.fetch(query as Record<string, unknown>) as Promise<TypedResult>;
    },
  };
}
