// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file tasks.proto (package ng.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "./google/api/annotations_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import { file_protograph_v1alpha1_options } from "./protograph/v1alpha1/options_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tasks.proto.
 */
export const file_tasks: GenFile = /*@__PURE__*/
  fileDesc("Cgt0YXNrcy5wcm90bxIFbmcudjEiigEKBFRhc2sSCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSDwoHY29udGVudBgDIAEoCRInCgpwcm9qZWN0X2lkGAQgASgJQhOCtRgPCg1uZy52MS5Qcm9qZWN0EiEKBnN0YXR1cxgFIAEoDjIRLm5nLnYxLlRhc2tTdGF0dXNKBAgGEAdKBAgHEAgifwoRQ3JlYXRlVGFza1JlcXVlc3QSFgoFdGl0bGUYASABKAlCB7pIBHICEAESDwoHY29udGVudBgCIAEoCRISCgpwcm9qZWN0X2lkGAMgASgJEiEKBnN0YXR1cxgEIAEoDjIRLm5nLnYxLlRhc2tTdGF0dXNKBAgFEAZKBAgGEAciJQoOR2V0VGFza1JlcXVlc3QSEwoCaWQYASABKAlCB7pIBHICEAEiJgoQTGlzdFRhc2tzUmVxdWVzdBISCgpwcm9qZWN0X2lkGAEgASgJIi8KEUxpc3RUYXNrc1Jlc3BvbnNlEhoKBXRhc2tzGAEgAygLMgsubmcudjEuVGFzayKUAQoRVXBkYXRlVGFza1JlcXVlc3QSEwoCaWQYASABKAlCB7pIBHICEAESFgoFdGl0bGUYAiABKAlCB7pIBHICEAESDwoHY29udGVudBgDIAEoCRISCgpwcm9qZWN0X2lkGAQgASgJEiEKBnN0YXR1cxgFIAEoDjIRLm5nLnYxLlRhc2tTdGF0dXNKBAgGEAdKBAgHEAgiKAoRRGVsZXRlVGFza1JlcXVlc3QSEwoCaWQYASABKAlCB7pIBHICEAEqcgoKVGFza1N0YXR1cxIbChdUQVNLX1NUQVRVU19VTlNQRUNJRklFRBAAEhQKEFRBU0tfU1RBVFVTX1RPRE8QARIbChdUQVNLX1NUQVRVU19JTl9QUk9HUkVTUxACEhQKEFRBU0tfU1RBVFVTX0RPTkUQAzKZAwoLVGFza1NlcnZpY2USSQoGQ3JlYXRlEhgubmcudjEuQ3JlYXRlVGFza1JlcXVlc3QaCy5uZy52MS5UYXNrIhiC0+STAhI6ASoiDS9hcGkvdjEvdGFza3MSRQoDR2V0EhUubmcudjEuR2V0VGFza1JlcXVlc3QaCy5uZy52MS5UYXNrIhqC0+STAhQSEi9hcGkvdjEvdGFza3Mve2lkfRJQCgRMaXN0EhcubmcudjEuTGlzdFRhc2tzUmVxdWVzdBoYLm5nLnYxLkxpc3RUYXNrc1Jlc3BvbnNlIhWC0+STAg8SDS9hcGkvdjEvdGFza3MSTgoGVXBkYXRlEhgubmcudjEuVXBkYXRlVGFza1JlcXVlc3QaCy5uZy52MS5UYXNrIh2C0+STAhc6ASoaEi9hcGkvdjEvdGFza3Mve2lkfRJWCgZEZWxldGUSGC5uZy52MS5EZWxldGVUYXNrUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIagtPkkwIUKhIvYXBpL3YxL3Rhc2tzL3tpZH1CKVonZ2l0aHViLmNvbS9saWFtYXdoaXRlL25nL2FwaS9nb2xhbmc7YXBpYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_empty, file_buf_validate_validate, file_protograph_v1alpha1_options]);

/**
 * @generated from message ng.v1.Task
 */
export type Task = Message<"ng.v1.Task"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * part_of project
   *
   * @generated from field: string project_id = 4;
   */
  projectId: string;

  /**
   * @generated from field: ng.v1.TaskStatus status = 5;
   */
  status: TaskStatus;
};

/**
 * Describes the message ng.v1.Task.
 * Use `create(TaskSchema)` to create a new message.
 */
export const TaskSchema: GenMessage<Task> = /*@__PURE__*/
  messageDesc(file_tasks, 0);

/**
 * @generated from message ng.v1.CreateTaskRequest
 */
export type CreateTaskRequest = Message<"ng.v1.CreateTaskRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: string project_id = 3;
   */
  projectId: string;

  /**
   * @generated from field: ng.v1.TaskStatus status = 4;
   */
  status: TaskStatus;
};

/**
 * Describes the message ng.v1.CreateTaskRequest.
 * Use `create(CreateTaskRequestSchema)` to create a new message.
 */
export const CreateTaskRequestSchema: GenMessage<CreateTaskRequest> = /*@__PURE__*/
  messageDesc(file_tasks, 1);

/**
 * @generated from message ng.v1.GetTaskRequest
 */
export type GetTaskRequest = Message<"ng.v1.GetTaskRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message ng.v1.GetTaskRequest.
 * Use `create(GetTaskRequestSchema)` to create a new message.
 */
export const GetTaskRequestSchema: GenMessage<GetTaskRequest> = /*@__PURE__*/
  messageDesc(file_tasks, 2);

/**
 * @generated from message ng.v1.ListTasksRequest
 */
export type ListTasksRequest = Message<"ng.v1.ListTasksRequest"> & {
  /**
   * optional filter
   *
   * @generated from field: string project_id = 1;
   */
  projectId: string;
};

/**
 * Describes the message ng.v1.ListTasksRequest.
 * Use `create(ListTasksRequestSchema)` to create a new message.
 */
export const ListTasksRequestSchema: GenMessage<ListTasksRequest> = /*@__PURE__*/
  messageDesc(file_tasks, 3);

/**
 * @generated from message ng.v1.ListTasksResponse
 */
export type ListTasksResponse = Message<"ng.v1.ListTasksResponse"> & {
  /**
   * @generated from field: repeated ng.v1.Task tasks = 1;
   */
  tasks: Task[];
};

/**
 * Describes the message ng.v1.ListTasksResponse.
 * Use `create(ListTasksResponseSchema)` to create a new message.
 */
export const ListTasksResponseSchema: GenMessage<ListTasksResponse> = /*@__PURE__*/
  messageDesc(file_tasks, 4);

/**
 * @generated from message ng.v1.UpdateTaskRequest
 */
export type UpdateTaskRequest = Message<"ng.v1.UpdateTaskRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: string project_id = 4;
   */
  projectId: string;

  /**
   * @generated from field: ng.v1.TaskStatus status = 5;
   */
  status: TaskStatus;
};

/**
 * Describes the message ng.v1.UpdateTaskRequest.
 * Use `create(UpdateTaskRequestSchema)` to create a new message.
 */
export const UpdateTaskRequestSchema: GenMessage<UpdateTaskRequest> = /*@__PURE__*/
  messageDesc(file_tasks, 5);

/**
 * @generated from message ng.v1.DeleteTaskRequest
 */
export type DeleteTaskRequest = Message<"ng.v1.DeleteTaskRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message ng.v1.DeleteTaskRequest.
 * Use `create(DeleteTaskRequestSchema)` to create a new message.
 */
export const DeleteTaskRequestSchema: GenMessage<DeleteTaskRequest> = /*@__PURE__*/
  messageDesc(file_tasks, 6);

/**
 * @generated from enum ng.v1.TaskStatus
 */
export enum TaskStatus {
  /**
   * @generated from enum value: TASK_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TASK_STATUS_TODO = 1;
   */
  TODO = 1,

  /**
   * @generated from enum value: TASK_STATUS_IN_PROGRESS = 2;
   */
  IN_PROGRESS = 2,

  /**
   * @generated from enum value: TASK_STATUS_DONE = 3;
   */
  DONE = 3,
}

/**
 * Describes the enum ng.v1.TaskStatus.
 */
export const TaskStatusSchema: GenEnum<TaskStatus> = /*@__PURE__*/
  enumDesc(file_tasks, 0);

/**
 * @generated from service ng.v1.TaskService
 */
export const TaskService: GenService<{
  /**
   * @generated from rpc ng.v1.TaskService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateTaskRequestSchema;
    output: typeof TaskSchema;
  },
  /**
   * @generated from rpc ng.v1.TaskService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetTaskRequestSchema;
    output: typeof TaskSchema;
  },
  /**
   * @generated from rpc ng.v1.TaskService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListTasksRequestSchema;
    output: typeof ListTasksResponseSchema;
  },
  /**
   * @generated from rpc ng.v1.TaskService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateTaskRequestSchema;
    output: typeof TaskSchema;
  },
  /**
   * @generated from rpc ng.v1.TaskService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteTaskRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tasks, 0);

