// Code generated by protograph-gen-ts. DO NOT EDIT.
// source: tasks.proto

import { createClient as createGenericClient } from "../../protograph/ts/client.js";

export interface TaskFields {
  id?: Record<string, never>;
  title?: Record<string, never>;
  content?: Record<string, never>;
  projectId?: Record<string, never>;
  status?: Record<string, never>;
  parentTaskId?: Record<string, never>;
  completed?: TimestampFields;
  pinned?: Record<string, never>;
  priority?: Record<string, never>;
  tasks?: TaskFields;
}

export interface CreateTaskRequestFields {
  title?: Record<string, never>;
  content?: Record<string, never>;
  projectId?: Record<string, never>;
  status?: Record<string, never>;
  parentTaskId?: Record<string, never>;
  pinned?: Record<string, never>;
  priority?: Record<string, never>;
}

export interface GetTaskRequestFields {
  id?: Record<string, never>;
}

export interface ListTasksRequestFields {
  projectId?: Record<string, never>;
  parentTaskId?: Record<string, never>;
  pinned?: Record<string, never>;
}

export interface ListTasksResponseFields {
  tasks?: TaskFields;
}

export interface UpdateTaskRequestFields {
  id?: Record<string, never>;
  title?: Record<string, never>;
  content?: Record<string, never>;
  projectId?: Record<string, never>;
  status?: Record<string, never>;
  parentTaskId?: Record<string, never>;
  updateMask?: FieldMaskFields;
  pinned?: Record<string, never>;
  priority?: Record<string, never>;
}

export interface DeleteTaskRequestFields {
  id?: Record<string, never>;
}

export interface TaskResult {
  id?: string;
  title?: string;
  content?: string;
  projectId?: string;
  status?: number;
  parentTaskId?: string;
  completed?: TimestampResult;
  pinned?: boolean;
  priority?: number;
  tasks?: TaskResult[];
}

export interface CreateTaskRequestResult {
  title?: string;
  content?: string;
  projectId?: string;
  status?: number;
  parentTaskId?: string;
  pinned?: boolean;
  priority?: number;
}

export interface GetTaskRequestResult {
  id?: string;
}

export interface ListTasksRequestResult {
  projectId?: string;
  parentTaskId?: string;
  pinned?: boolean;
}

export interface ListTasksResponseResult {
  tasks?: TaskResult[];
}

export interface UpdateTaskRequestResult {
  id?: string;
  title?: string;
  content?: string;
  projectId?: string;
  status?: number;
  parentTaskId?: string;
  updateMask?: FieldMaskResult;
  pinned?: boolean;
  priority?: number;
}

export interface DeleteTaskRequestResult {
  id?: string;
}

export type TaskServiceQuery = {
  create?: {
    $?: Partial<CreateTaskRequestResult>;
  } & TaskFields;
  get?: {
    $?: Partial<GetTaskRequestResult>;
  } & TaskFields;
  list?: {
    $?: Partial<ListTasksRequestResult>;
  } & ListTasksResponseFields;
  update?: {
    $?: Partial<UpdateTaskRequestResult>;
  } & TaskFields;
  delete?: {
    $?: Partial<DeleteTaskRequestResult>;
  } & EmptyFields;
};

export type TaskServiceResult = {
  create?: TaskResult;
  get?: TaskResult;
  list?: ListTasksResponseResult;
  update?: TaskResult;
  delete?: EmptyResult;
};

export type TypedQuery = {
  "ng.v1.TaskService"?: TaskServiceQuery;
};

export type TypedResult = {
  "ng.v1.TaskService"?: TaskServiceResult;
};

/**
 * createClient returns a typed protograph client.
 * @param baseURL Base URL of the backend, e.g. "http://localhost:8080"
 */
export function createClient(baseURL: string) {
  const generic = createGenericClient(baseURL);
  return {
    async fetch(query: TypedQuery): Promise<TypedResult> {
      return generic.fetch(query as Record<string, unknown>) as Promise<TypedResult>;
    },
  };
}
