// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file tasks.proto (package ng.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTaskRequest, DeleteTaskRequest, GetTaskRequest, ListTasksRequest, ListTasksResponse, Task, UpdateTaskRequest } from "./tasks_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ng.v1.TaskService
 */
export const TaskService = {
  typeName: "ng.v1.TaskService",
  methods: {
    /**
     * @generated from rpc ng.v1.TaskService.Create
     */
    create: {
      name: "Create",
      I: CreateTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.Get
     */
    get: {
      name: "Get",
      I: GetTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.List
     */
    list: {
      name: "List",
      I: ListTasksRequest,
      O: ListTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.Update
     */
    update: {
      name: "Update",
      I: UpdateTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ng.v1.TaskService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteTaskRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

