// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: areas.proto

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_areas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{0}
}

func (x *Area) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Area) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAreaRequest) Reset() {
	*x = CreateAreaRequest{}
	mi := &file_areas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaRequest) ProtoMessage() {}

func (x *CreateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateAreaRequest) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAreaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAreaRequest) Reset() {
	*x = GetAreaRequest{}
	mi := &file_areas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaRequest) ProtoMessage() {}

func (x *GetAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaRequest.ProtoReflect.Descriptor instead.
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{2}
}

func (x *GetAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAreasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreasRequest) Reset() {
	*x = ListAreasRequest{}
	mi := &file_areas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreasRequest) ProtoMessage() {}

func (x *ListAreasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreasRequest.ProtoReflect.Descriptor instead.
func (*ListAreasRequest) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{3}
}

type ListAreasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*Area                `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreasResponse) Reset() {
	*x = ListAreasResponse{}
	mi := &file_areas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreasResponse) ProtoMessage() {}

func (x *ListAreasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreasResponse.ProtoReflect.Descriptor instead.
func (*ListAreasResponse) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{4}
}

func (x *ListAreasResponse) GetAreas() []*Area {
	if x != nil {
		return x.Areas
	}
	return nil
}

type UpdateAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAreaRequest) Reset() {
	*x = UpdateAreaRequest{}
	mi := &file_areas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaRequest) ProtoMessage() {}

func (x *UpdateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaRequest) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAreaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAreaRequest) Reset() {
	*x = DeleteAreaRequest{}
	mi := &file_areas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaRequest) ProtoMessage() {}

func (x *DeleteAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_areas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaRequest.ProtoReflect.Descriptor instead.
func (*DeleteAreaRequest) Descriptor() ([]byte, []int) {
	return file_areas_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_areas_proto protoreflect.FileDescriptor

const file_areas_proto_rawDesc = "" +
	"\n" +
	"\vareas.proto\x12\x05ng.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bbuf/validate/validate.proto\",\n" +
	"\x04Area\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"2\n" +
	"\x11CreateAreaRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\")\n" +
	"\x0eGetAreaRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x12\n" +
	"\x10ListAreasRequest\"6\n" +
	"\x11ListAreasResponse\x12!\n" +
	"\x05areas\x18\x01 \x03(\v2\v.ng.v1.AreaR\x05areas\"K\n" +
	"\x11UpdateAreaRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\",\n" +
	"\x11DeleteAreaRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id2\x99\x03\n" +
	"\vAreaService\x12I\n" +
	"\x06Create\x12\x18.ng.v1.CreateAreaRequest\x1a\v.ng.v1.Area\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/areas\x12E\n" +
	"\x03Get\x12\x15.ng.v1.GetAreaRequest\x1a\v.ng.v1.Area\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/areas/{id}\x12P\n" +
	"\x04List\x12\x17.ng.v1.ListAreasRequest\x1a\x18.ng.v1.ListAreasResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/areas\x12N\n" +
	"\x06Update\x12\x18.ng.v1.UpdateAreaRequest\x1a\v.ng.v1.Area\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/areas/{id}\x12V\n" +
	"\x06Delete\x12\x18.ng.v1.DeleteAreaRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/areas/{id}B)Z'github.com/liamawhite/ng/api/golang;apib\x06proto3"

var (
	file_areas_proto_rawDescOnce sync.Once
	file_areas_proto_rawDescData []byte
)

func file_areas_proto_rawDescGZIP() []byte {
	file_areas_proto_rawDescOnce.Do(func() {
		file_areas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_areas_proto_rawDesc), len(file_areas_proto_rawDesc)))
	})
	return file_areas_proto_rawDescData
}

var file_areas_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_areas_proto_goTypes = []any{
	(*Area)(nil),              // 0: ng.v1.Area
	(*CreateAreaRequest)(nil), // 1: ng.v1.CreateAreaRequest
	(*GetAreaRequest)(nil),    // 2: ng.v1.GetAreaRequest
	(*ListAreasRequest)(nil),  // 3: ng.v1.ListAreasRequest
	(*ListAreasResponse)(nil), // 4: ng.v1.ListAreasResponse
	(*UpdateAreaRequest)(nil), // 5: ng.v1.UpdateAreaRequest
	(*DeleteAreaRequest)(nil), // 6: ng.v1.DeleteAreaRequest
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_areas_proto_depIdxs = []int32{
	0, // 0: ng.v1.ListAreasResponse.areas:type_name -> ng.v1.Area
	1, // 1: ng.v1.AreaService.Create:input_type -> ng.v1.CreateAreaRequest
	2, // 2: ng.v1.AreaService.Get:input_type -> ng.v1.GetAreaRequest
	3, // 3: ng.v1.AreaService.List:input_type -> ng.v1.ListAreasRequest
	5, // 4: ng.v1.AreaService.Update:input_type -> ng.v1.UpdateAreaRequest
	6, // 5: ng.v1.AreaService.Delete:input_type -> ng.v1.DeleteAreaRequest
	0, // 6: ng.v1.AreaService.Create:output_type -> ng.v1.Area
	0, // 7: ng.v1.AreaService.Get:output_type -> ng.v1.Area
	4, // 8: ng.v1.AreaService.List:output_type -> ng.v1.ListAreasResponse
	0, // 9: ng.v1.AreaService.Update:output_type -> ng.v1.Area
	7, // 10: ng.v1.AreaService.Delete:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_areas_proto_init() }
func file_areas_proto_init() {
	if File_areas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_areas_proto_rawDesc), len(file_areas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_areas_proto_goTypes,
		DependencyIndexes: file_areas_proto_depIdxs,
		MessageInfos:      file_areas_proto_msgTypes,
	}.Build()
	File_areas_proto = out.File
	file_areas_proto_goTypes = nil
	file_areas_proto_depIdxs = nil
}
