// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph.proto

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Predicate int32

const (
	Predicate_PREDICATE_UNSPECIFIED Predicate = 0 // matches all predicates in ListRelated
	Predicate_PREDICATE_PART_OF     Predicate = 1
	Predicate_PREDICATE_IN_AREA     Predicate = 2
	Predicate_PREDICATE_TASK        Predicate = 3 // project → task
	Predicate_PREDICATE_SUBTASK     Predicate = 4 // task → subtask
	Predicate_PREDICATE_SUBPROJECT  Predicate = 5 // project → subproject
)

// Enum value maps for Predicate.
var (
	Predicate_name = map[int32]string{
		0: "PREDICATE_UNSPECIFIED",
		1: "PREDICATE_PART_OF",
		2: "PREDICATE_IN_AREA",
		3: "PREDICATE_TASK",
		4: "PREDICATE_SUBTASK",
		5: "PREDICATE_SUBPROJECT",
	}
	Predicate_value = map[string]int32{
		"PREDICATE_UNSPECIFIED": 0,
		"PREDICATE_PART_OF":     1,
		"PREDICATE_IN_AREA":     2,
		"PREDICATE_TASK":        3,
		"PREDICATE_SUBTASK":     4,
		"PREDICATE_SUBPROJECT":  5,
	}
)

func (x Predicate) Enum() *Predicate {
	p := new(Predicate)
	*p = x
	return p
}

func (x Predicate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Predicate) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_proto_enumTypes[0].Descriptor()
}

func (Predicate) Type() protoreflect.EnumType {
	return &file_graph_proto_enumTypes[0]
}

func (x Predicate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Predicate.Descriptor instead.
func (Predicate) EnumDescriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_OUTGOING    Direction = 1 // id is the source of the relationship
	Direction_DIRECTION_INCOMING    Direction = 2 // id is the target of the relationship
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_OUTGOING",
		2: "DIRECTION_INCOMING",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_OUTGOING":    1,
		"DIRECTION_INCOMING":    2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_graph_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*Entity_Project
	//	*Entity_Task
	//	*Entity_Area
	Entity        isEntity_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetEntity() isEntity_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *Entity) GetProject() *Project {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *Entity) GetTask() *Task {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *Entity) GetArea() *Area {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Area); ok {
			return x.Area
		}
	}
	return nil
}

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_Project struct {
	Project *Project `protobuf:"bytes,1,opt,name=project,proto3,oneof"`
}

type Entity_Task struct {
	Task *Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type Entity_Area struct {
	Area *Area `protobuf:"bytes,3,opt,name=area,proto3,oneof"`
}

func (*Entity_Project) isEntity_Entity() {}

func (*Entity_Task) isEntity_Entity() {}

func (*Entity_Area) isEntity_Entity() {}

type ListRelatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Predicate     Predicate              `protobuf:"varint,2,opt,name=predicate,proto3,enum=ng.v1.Predicate" json:"predicate,omitempty"` // UNSPECIFIED = all predicates
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=ng.v1.Direction" json:"direction,omitempty"` // UNSPECIFIED = both directions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedRequest) Reset() {
	*x = ListRelatedRequest{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedRequest) ProtoMessage() {}

func (x *ListRelatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedRequest.ProtoReflect.Descriptor instead.
func (*ListRelatedRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *ListRelatedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListRelatedRequest) GetPredicate() Predicate {
	if x != nil {
		return x.Predicate
	}
	return Predicate_PREDICATE_UNSPECIFIED
}

func (x *ListRelatedRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type ListRelatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*RelatedEntity       `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedResponse) Reset() {
	*x = ListRelatedResponse{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedResponse) ProtoMessage() {}

func (x *ListRelatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedResponse.ProtoReflect.Descriptor instead.
func (*ListRelatedResponse) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *ListRelatedResponse) GetEntities() []*RelatedEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RelatedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predicate     Predicate              `protobuf:"varint,1,opt,name=predicate,proto3,enum=ng.v1.Predicate" json:"predicate,omitempty"` // the relationship predicate
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=ng.v1.Direction" json:"direction,omitempty"` // which direction the edge runs relative to the queried id
	Entity        *Entity                `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`                             // the related entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedEntity) Reset() {
	*x = RelatedEntity{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedEntity) ProtoMessage() {}

func (x *RelatedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedEntity.ProtoReflect.Descriptor instead.
func (*RelatedEntity) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *RelatedEntity) GetPredicate() Predicate {
	if x != nil {
		return x.Predicate
	}
	return Predicate_PREDICATE_UNSPECIFIED
}

func (x *RelatedEntity) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *RelatedEntity) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\x05ng.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\vareas.proto\x1a\x0eprojects.proto\x1a\vtasks.proto\"\x84\x01\n" +
	"\x06Entity\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x0e.ng.v1.ProjectH\x00R\aproject\x12!\n" +
	"\x04task\x18\x02 \x01(\v2\v.ng.v1.TaskH\x00R\x04task\x12!\n" +
	"\x04area\x18\x03 \x01(\v2\v.ng.v1.AreaH\x00R\x04areaB\b\n" +
	"\x06entity\"\x8d\x01\n" +
	"\x12ListRelatedRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12.\n" +
	"\tpredicate\x18\x02 \x01(\x0e2\x10.ng.v1.PredicateR\tpredicate\x12.\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x10.ng.v1.DirectionR\tdirection\"G\n" +
	"\x13ListRelatedResponse\x120\n" +
	"\bentities\x18\x01 \x03(\v2\x14.ng.v1.RelatedEntityR\bentities\"\x96\x01\n" +
	"\rRelatedEntity\x12.\n" +
	"\tpredicate\x18\x01 \x01(\x0e2\x10.ng.v1.PredicateR\tpredicate\x12.\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x10.ng.v1.DirectionR\tdirection\x12%\n" +
	"\x06entity\x18\x03 \x01(\v2\r.ng.v1.EntityR\x06entity*\x99\x01\n" +
	"\tPredicate\x12\x19\n" +
	"\x15PREDICATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PREDICATE_PART_OF\x10\x01\x12\x15\n" +
	"\x11PREDICATE_IN_AREA\x10\x02\x12\x12\n" +
	"\x0ePREDICATE_TASK\x10\x03\x12\x15\n" +
	"\x11PREDICATE_SUBTASK\x10\x04\x12\x18\n" +
	"\x14PREDICATE_SUBPROJECT\x10\x05*V\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DIRECTION_OUTGOING\x10\x01\x12\x16\n" +
	"\x12DIRECTION_INCOMING\x10\x022x\n" +
	"\fGraphService\x12h\n" +
	"\vListRelated\x12\x19.ng.v1.ListRelatedRequest\x1a\x1a.ng.v1.ListRelatedResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/graph/{id}/relatedB)Z'github.com/liamawhite/ng/api/golang;apib\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_proto_goTypes = []any{
	(Predicate)(0),              // 0: ng.v1.Predicate
	(Direction)(0),              // 1: ng.v1.Direction
	(*Entity)(nil),              // 2: ng.v1.Entity
	(*ListRelatedRequest)(nil),  // 3: ng.v1.ListRelatedRequest
	(*ListRelatedResponse)(nil), // 4: ng.v1.ListRelatedResponse
	(*RelatedEntity)(nil),       // 5: ng.v1.RelatedEntity
	(*Project)(nil),             // 6: ng.v1.Project
	(*Task)(nil),                // 7: ng.v1.Task
	(*Area)(nil),                // 8: ng.v1.Area
}
var file_graph_proto_depIdxs = []int32{
	6,  // 0: ng.v1.Entity.project:type_name -> ng.v1.Project
	7,  // 1: ng.v1.Entity.task:type_name -> ng.v1.Task
	8,  // 2: ng.v1.Entity.area:type_name -> ng.v1.Area
	0,  // 3: ng.v1.ListRelatedRequest.predicate:type_name -> ng.v1.Predicate
	1,  // 4: ng.v1.ListRelatedRequest.direction:type_name -> ng.v1.Direction
	5,  // 5: ng.v1.ListRelatedResponse.entities:type_name -> ng.v1.RelatedEntity
	0,  // 6: ng.v1.RelatedEntity.predicate:type_name -> ng.v1.Predicate
	1,  // 7: ng.v1.RelatedEntity.direction:type_name -> ng.v1.Direction
	2,  // 8: ng.v1.RelatedEntity.entity:type_name -> ng.v1.Entity
	3,  // 9: ng.v1.GraphService.ListRelated:input_type -> ng.v1.ListRelatedRequest
	4,  // 10: ng.v1.GraphService.ListRelated:output_type -> ng.v1.ListRelatedResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	file_areas_proto_init()
	file_projects_proto_init()
	file_tasks_proto_init()
	file_graph_proto_msgTypes[0].OneofWrappers = []any{
		(*Entity_Project)(nil),
		(*Entity_Task)(nil),
		(*Entity_Area)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		EnumInfos:         file_graph_proto_enumTypes,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
