// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ng.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_TODO        TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_TODO",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_DONE",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_TODO":        1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_DONE":        3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ng_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_ng_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{0}
}

type Predicate int32

const (
	Predicate_PREDICATE_UNSPECIFIED Predicate = 0 // matches all predicates in ListRelated
	Predicate_PREDICATE_PART_OF     Predicate = 1
)

// Enum value maps for Predicate.
var (
	Predicate_name = map[int32]string{
		0: "PREDICATE_UNSPECIFIED",
		1: "PREDICATE_PART_OF",
	}
	Predicate_value = map[string]int32{
		"PREDICATE_UNSPECIFIED": 0,
		"PREDICATE_PART_OF":     1,
	}
)

func (x Predicate) Enum() *Predicate {
	p := new(Predicate)
	*p = x
	return p
}

func (x Predicate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Predicate) Descriptor() protoreflect.EnumDescriptor {
	return file_ng_proto_enumTypes[1].Descriptor()
}

func (Predicate) Type() protoreflect.EnumType {
	return &file_ng_proto_enumTypes[1]
}

func (x Predicate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Predicate.Descriptor instead.
func (Predicate) EnumDescriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_OUTGOING    Direction = 1 // id is the source of the relationship
	Direction_DIRECTION_INCOMING    Direction = 2 // id is the target of the relationship
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_OUTGOING",
		2: "DIRECTION_INCOMING",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_OUTGOING":    1,
		"DIRECTION_INCOMING":    2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_ng_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_ng_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{2}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // empty if top-level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_ng_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Project) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // part_of project
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=ng.v1.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_ng_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_ng_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProjectRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateProjectRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_ng_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_ng_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_ng_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_ng_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProjectRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateProjectRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_ng_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=ng.v1.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_ng_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_ng_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_ng_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_ng_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=ng.v1.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_ng_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_ng_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*Entity_Project
	//	*Entity_Task
	Entity        isEntity_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_ng_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{14}
}

func (x *Entity) GetEntity() isEntity_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *Entity) GetProject() *Project {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *Entity) GetTask() *Task {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Task); ok {
			return x.Task
		}
	}
	return nil
}

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_Project struct {
	Project *Project `protobuf:"bytes,1,opt,name=project,proto3,oneof"`
}

type Entity_Task struct {
	Task *Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

func (*Entity_Project) isEntity_Entity() {}

func (*Entity_Task) isEntity_Entity() {}

type ListRelatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Predicate     Predicate              `protobuf:"varint,2,opt,name=predicate,proto3,enum=ng.v1.Predicate" json:"predicate,omitempty"` // UNSPECIFIED = all predicates
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=ng.v1.Direction" json:"direction,omitempty"` // UNSPECIFIED = both directions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedRequest) Reset() {
	*x = ListRelatedRequest{}
	mi := &file_ng_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedRequest) ProtoMessage() {}

func (x *ListRelatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedRequest.ProtoReflect.Descriptor instead.
func (*ListRelatedRequest) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{15}
}

func (x *ListRelatedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListRelatedRequest) GetPredicate() Predicate {
	if x != nil {
		return x.Predicate
	}
	return Predicate_PREDICATE_UNSPECIFIED
}

func (x *ListRelatedRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type ListRelatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*RelatedEntity       `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedResponse) Reset() {
	*x = ListRelatedResponse{}
	mi := &file_ng_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedResponse) ProtoMessage() {}

func (x *ListRelatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedResponse.ProtoReflect.Descriptor instead.
func (*ListRelatedResponse) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{16}
}

func (x *ListRelatedResponse) GetEntities() []*RelatedEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RelatedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predicate     Predicate              `protobuf:"varint,1,opt,name=predicate,proto3,enum=ng.v1.Predicate" json:"predicate,omitempty"` // the relationship predicate
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=ng.v1.Direction" json:"direction,omitempty"` // which direction the edge runs relative to the queried id
	Entity        *Entity                `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`                             // the related entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedEntity) Reset() {
	*x = RelatedEntity{}
	mi := &file_ng_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedEntity) ProtoMessage() {}

func (x *RelatedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_ng_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedEntity.ProtoReflect.Descriptor instead.
func (*RelatedEntity) Descriptor() ([]byte, []int) {
	return file_ng_proto_rawDescGZIP(), []int{17}
}

func (x *RelatedEntity) GetPredicate() Predicate {
	if x != nil {
		return x.Predicate
	}
	return Predicate_PREDICATE_UNSPECIFIED
}

func (x *RelatedEntity) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *RelatedEntity) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_ng_proto protoreflect.FileDescriptor

const file_ng_proto_rawDesc = "" +
	"\n" +
	"\bng.proto\x12\x05ng.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"f\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"\x90\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.ng.v1.TaskStatusR\x06status\"c\n" +
	"\x14CreateProjectRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\"B\n" +
	"\x14ListProjectsResponse\x12*\n" +
	"\bprojects\x18\x01 \x03(\v2\x0e.ng.v1.ProjectR\bprojects\"s\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"&\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8d\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.ng.v1.TaskStatusR\x06status\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"6\n" +
	"\x11ListTasksResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.ng.v1.TaskR\x05tasks\"\x9d\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.ng.v1.TaskStatusR\x06status\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\x06Entity\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x0e.ng.v1.ProjectH\x00R\aproject\x12!\n" +
	"\x04task\x18\x02 \x01(\v2\v.ng.v1.TaskH\x00R\x04taskB\b\n" +
	"\x06entity\"\x84\x01\n" +
	"\x12ListRelatedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\tpredicate\x18\x02 \x01(\x0e2\x10.ng.v1.PredicateR\tpredicate\x12.\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x10.ng.v1.DirectionR\tdirection\"G\n" +
	"\x13ListRelatedResponse\x120\n" +
	"\bentities\x18\x01 \x03(\v2\x14.ng.v1.RelatedEntityR\bentities\"\x96\x01\n" +
	"\rRelatedEntity\x12.\n" +
	"\tpredicate\x18\x01 \x01(\x0e2\x10.ng.v1.PredicateR\tpredicate\x12.\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x10.ng.v1.DirectionR\tdirection\x12%\n" +
	"\x06entity\x18\x03 \x01(\v2\r.ng.v1.EntityR\x06entity*r\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_TODO\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x03*=\n" +
	"\tPredicate\x12\x19\n" +
	"\x15PREDICATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PREDICATE_PART_OF\x10\x01*V\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DIRECTION_OUTGOING\x10\x01\x12\x16\n" +
	"\x12DIRECTION_INCOMING\x10\x022\xc6\x03\n" +
	"\x0eProjectService\x12R\n" +
	"\x06Create\x12\x1b.ng.v1.CreateProjectRequest\x1a\x0e.ng.v1.Project\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/projects\x12N\n" +
	"\x03Get\x12\x18.ng.v1.GetProjectRequest\x1a\x0e.ng.v1.Project\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/projects/{id}\x12Y\n" +
	"\x04List\x12\x1a.ng.v1.ListProjectsRequest\x1a\x1b.ng.v1.ListProjectsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/projects\x12W\n" +
	"\x06Update\x12\x1b.ng.v1.UpdateProjectRequest\x1a\x0e.ng.v1.Project\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/projects/{id}\x12\\\n" +
	"\x06Delete\x12\x1b.ng.v1.DeleteProjectRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/projects/{id}2\x99\x03\n" +
	"\vTaskService\x12I\n" +
	"\x06Create\x12\x18.ng.v1.CreateTaskRequest\x1a\v.ng.v1.Task\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12E\n" +
	"\x03Get\x12\x15.ng.v1.GetTaskRequest\x1a\v.ng.v1.Task\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tasks/{id}\x12P\n" +
	"\x04List\x12\x17.ng.v1.ListTasksRequest\x1a\x18.ng.v1.ListTasksResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/tasks\x12N\n" +
	"\x06Update\x12\x18.ng.v1.UpdateTaskRequest\x1a\v.ng.v1.Task\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/tasks/{id}\x12V\n" +
	"\x06Delete\x12\x18.ng.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/tasks/{id}2x\n" +
	"\fGraphService\x12h\n" +
	"\vListRelated\x12\x19.ng.v1.ListRelatedRequest\x1a\x1a.ng.v1.ListRelatedResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/graph/{id}/relatedB)Z'github.com/liamawhite/ng/api/golang;apib\x06proto3"

var (
	file_ng_proto_rawDescOnce sync.Once
	file_ng_proto_rawDescData []byte
)

func file_ng_proto_rawDescGZIP() []byte {
	file_ng_proto_rawDescOnce.Do(func() {
		file_ng_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ng_proto_rawDesc), len(file_ng_proto_rawDesc)))
	})
	return file_ng_proto_rawDescData
}

var file_ng_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ng_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ng_proto_goTypes = []any{
	(TaskStatus)(0),              // 0: ng.v1.TaskStatus
	(Predicate)(0),               // 1: ng.v1.Predicate
	(Direction)(0),               // 2: ng.v1.Direction
	(*Project)(nil),              // 3: ng.v1.Project
	(*Task)(nil),                 // 4: ng.v1.Task
	(*CreateProjectRequest)(nil), // 5: ng.v1.CreateProjectRequest
	(*GetProjectRequest)(nil),    // 6: ng.v1.GetProjectRequest
	(*ListProjectsRequest)(nil),  // 7: ng.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil), // 8: ng.v1.ListProjectsResponse
	(*UpdateProjectRequest)(nil), // 9: ng.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil), // 10: ng.v1.DeleteProjectRequest
	(*CreateTaskRequest)(nil),    // 11: ng.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),       // 12: ng.v1.GetTaskRequest
	(*ListTasksRequest)(nil),     // 13: ng.v1.ListTasksRequest
	(*ListTasksResponse)(nil),    // 14: ng.v1.ListTasksResponse
	(*UpdateTaskRequest)(nil),    // 15: ng.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),    // 16: ng.v1.DeleteTaskRequest
	(*Entity)(nil),               // 17: ng.v1.Entity
	(*ListRelatedRequest)(nil),   // 18: ng.v1.ListRelatedRequest
	(*ListRelatedResponse)(nil),  // 19: ng.v1.ListRelatedResponse
	(*RelatedEntity)(nil),        // 20: ng.v1.RelatedEntity
	(*emptypb.Empty)(nil),        // 21: google.protobuf.Empty
}
var file_ng_proto_depIdxs = []int32{
	0,  // 0: ng.v1.Task.status:type_name -> ng.v1.TaskStatus
	3,  // 1: ng.v1.ListProjectsResponse.projects:type_name -> ng.v1.Project
	0,  // 2: ng.v1.CreateTaskRequest.status:type_name -> ng.v1.TaskStatus
	4,  // 3: ng.v1.ListTasksResponse.tasks:type_name -> ng.v1.Task
	0,  // 4: ng.v1.UpdateTaskRequest.status:type_name -> ng.v1.TaskStatus
	3,  // 5: ng.v1.Entity.project:type_name -> ng.v1.Project
	4,  // 6: ng.v1.Entity.task:type_name -> ng.v1.Task
	1,  // 7: ng.v1.ListRelatedRequest.predicate:type_name -> ng.v1.Predicate
	2,  // 8: ng.v1.ListRelatedRequest.direction:type_name -> ng.v1.Direction
	20, // 9: ng.v1.ListRelatedResponse.entities:type_name -> ng.v1.RelatedEntity
	1,  // 10: ng.v1.RelatedEntity.predicate:type_name -> ng.v1.Predicate
	2,  // 11: ng.v1.RelatedEntity.direction:type_name -> ng.v1.Direction
	17, // 12: ng.v1.RelatedEntity.entity:type_name -> ng.v1.Entity
	5,  // 13: ng.v1.ProjectService.Create:input_type -> ng.v1.CreateProjectRequest
	6,  // 14: ng.v1.ProjectService.Get:input_type -> ng.v1.GetProjectRequest
	7,  // 15: ng.v1.ProjectService.List:input_type -> ng.v1.ListProjectsRequest
	9,  // 16: ng.v1.ProjectService.Update:input_type -> ng.v1.UpdateProjectRequest
	10, // 17: ng.v1.ProjectService.Delete:input_type -> ng.v1.DeleteProjectRequest
	11, // 18: ng.v1.TaskService.Create:input_type -> ng.v1.CreateTaskRequest
	12, // 19: ng.v1.TaskService.Get:input_type -> ng.v1.GetTaskRequest
	13, // 20: ng.v1.TaskService.List:input_type -> ng.v1.ListTasksRequest
	15, // 21: ng.v1.TaskService.Update:input_type -> ng.v1.UpdateTaskRequest
	16, // 22: ng.v1.TaskService.Delete:input_type -> ng.v1.DeleteTaskRequest
	18, // 23: ng.v1.GraphService.ListRelated:input_type -> ng.v1.ListRelatedRequest
	3,  // 24: ng.v1.ProjectService.Create:output_type -> ng.v1.Project
	3,  // 25: ng.v1.ProjectService.Get:output_type -> ng.v1.Project
	8,  // 26: ng.v1.ProjectService.List:output_type -> ng.v1.ListProjectsResponse
	3,  // 27: ng.v1.ProjectService.Update:output_type -> ng.v1.Project
	21, // 28: ng.v1.ProjectService.Delete:output_type -> google.protobuf.Empty
	4,  // 29: ng.v1.TaskService.Create:output_type -> ng.v1.Task
	4,  // 30: ng.v1.TaskService.Get:output_type -> ng.v1.Task
	14, // 31: ng.v1.TaskService.List:output_type -> ng.v1.ListTasksResponse
	4,  // 32: ng.v1.TaskService.Update:output_type -> ng.v1.Task
	21, // 33: ng.v1.TaskService.Delete:output_type -> google.protobuf.Empty
	19, // 34: ng.v1.GraphService.ListRelated:output_type -> ng.v1.ListRelatedResponse
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ng_proto_init() }
func file_ng_proto_init() {
	if File_ng_proto != nil {
		return
	}
	file_ng_proto_msgTypes[14].OneofWrappers = []any{
		(*Entity_Project)(nil),
		(*Entity_Task)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ng_proto_rawDesc), len(file_ng_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_ng_proto_goTypes,
		DependencyIndexes: file_ng_proto_depIdxs,
		EnumInfos:         file_ng_proto_enumTypes,
		MessageInfos:      file_ng_proto_msgTypes,
	}.Build()
	File_ng_proto = out.File
	file_ng_proto_goTypes = nil
	file_ng_proto_depIdxs = nil
}
