// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: projects.proto

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/liamawhite/ng/api/golang/protograph/v1alpha1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_PROJECT_STATUS_ACTIVE      ProjectStatus = 1
	ProjectStatus_PROJECT_STATUS_BACKLOG     ProjectStatus = 2
	ProjectStatus_PROJECT_STATUS_BLOCKED     ProjectStatus = 3
	ProjectStatus_PROJECT_STATUS_COMPLETED   ProjectStatus = 4
	ProjectStatus_PROJECT_STATUS_ABANDONED   ProjectStatus = 5
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "PROJECT_STATUS_ACTIVE",
		2: "PROJECT_STATUS_BACKLOG",
		3: "PROJECT_STATUS_BLOCKED",
		4: "PROJECT_STATUS_COMPLETED",
		5: "PROJECT_STATUS_ABANDONED",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"PROJECT_STATUS_ACTIVE":      1,
		"PROJECT_STATUS_BACKLOG":     2,
		"PROJECT_STATUS_BLOCKED":     3,
		"PROJECT_STATUS_COMPLETED":   4,
		"PROJECT_STATUS_ABANDONED":   5,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_projects_proto_enumTypes[0].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_projects_proto_enumTypes[0]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{0}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // empty if top-level
	Status        ProjectStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=ng.v1.ProjectStatus" json:"status,omitempty"`
	AreaId        string                 `protobuf:"bytes,8,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Project) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Project) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *Project) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=ng.v1.ProjectStatus" json:"status,omitempty"`
	AreaId        string                 `protobuf:"bytes,7,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProjectRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateProjectRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateProjectRequest) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *CreateProjectRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_projects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`       // optional filter
	Status        ProjectStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=ng.v1.ProjectStatus" json:"status,omitempty"` // UNSPECIFIED = all statuses
	AreaId        string                 `protobuf:"bytes,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`             // empty = all areas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_projects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListProjectsRequest) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *ListProjectsRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_projects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=ng.v1.ProjectStatus" json:"status,omitempty"`
	AreaId        string                 `protobuf:"bytes,8,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_projects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProjectRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateProjectRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateProjectRequest) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *UpdateProjectRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_projects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_projects_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_projects_proto protoreflect.FileDescriptor

const file_projects_proto_rawDesc = "" +
	"\n" +
	"\x0eprojects.proto\x12\x05ng.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bbuf/validate/validate.proto\x1a!protograph/v1alpha1/options.proto\"\xe0\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x120\n" +
	"\tparent_id\x18\x04 \x01(\tB\x13\x82\xb5\x18\x0f\n" +
	"\rng.v1.ProjectR\bparentId\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.ng.v1.ProjectStatusR\x06status\x12)\n" +
	"\aarea_id\x18\b \x01(\tB\x10\x82\xb5\x18\f\n" +
	"\n" +
	"ng.v1.AreaR\x06areaIdJ\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\xbf\x01\n" +
	"\x14CreateProjectRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12,\n" +
	"\x06status\x18\x06 \x01(\x0e2\x14.ng.v1.ProjectStatusR\x06status\x12\x17\n" +
	"\aarea_id\x18\a \x01(\tR\x06areaIdJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\",\n" +
	"\x11GetProjectRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"y\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.ng.v1.ProjectStatusR\x06status\x12\x17\n" +
	"\aarea_id\x18\x03 \x01(\tR\x06areaId\"B\n" +
	"\x14ListProjectsResponse\x12*\n" +
	"\bprojects\x18\x01 \x03(\v2\x0e.ng.v1.ProjectR\bprojects\"\xd8\x01\n" +
	"\x14UpdateProjectRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.ng.v1.ProjectStatusR\x06status\x12\x17\n" +
	"\aarea_id\x18\b \x01(\tR\x06areaIdJ\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"/\n" +
	"\x14DeleteProjectRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id*\xbe\x01\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROJECT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16PROJECT_STATUS_BACKLOG\x10\x02\x12\x1a\n" +
	"\x16PROJECT_STATUS_BLOCKED\x10\x03\x12\x1c\n" +
	"\x18PROJECT_STATUS_COMPLETED\x10\x04\x12\x1c\n" +
	"\x18PROJECT_STATUS_ABANDONED\x10\x052\xc6\x03\n" +
	"\x0eProjectService\x12R\n" +
	"\x06Create\x12\x1b.ng.v1.CreateProjectRequest\x1a\x0e.ng.v1.Project\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/projects\x12N\n" +
	"\x03Get\x12\x18.ng.v1.GetProjectRequest\x1a\x0e.ng.v1.Project\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/projects/{id}\x12Y\n" +
	"\x04List\x12\x1a.ng.v1.ListProjectsRequest\x1a\x1b.ng.v1.ListProjectsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/projects\x12W\n" +
	"\x06Update\x12\x1b.ng.v1.UpdateProjectRequest\x1a\x0e.ng.v1.Project\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/projects/{id}\x12\\\n" +
	"\x06Delete\x12\x1b.ng.v1.DeleteProjectRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/projects/{id}B)Z'github.com/liamawhite/ng/api/golang;apib\x06proto3"

var (
	file_projects_proto_rawDescOnce sync.Once
	file_projects_proto_rawDescData []byte
)

func file_projects_proto_rawDescGZIP() []byte {
	file_projects_proto_rawDescOnce.Do(func() {
		file_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projects_proto_rawDesc), len(file_projects_proto_rawDesc)))
	})
	return file_projects_proto_rawDescData
}

var file_projects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_projects_proto_goTypes = []any{
	(ProjectStatus)(0),           // 0: ng.v1.ProjectStatus
	(*Project)(nil),              // 1: ng.v1.Project
	(*CreateProjectRequest)(nil), // 2: ng.v1.CreateProjectRequest
	(*GetProjectRequest)(nil),    // 3: ng.v1.GetProjectRequest
	(*ListProjectsRequest)(nil),  // 4: ng.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil), // 5: ng.v1.ListProjectsResponse
	(*UpdateProjectRequest)(nil), // 6: ng.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil), // 7: ng.v1.DeleteProjectRequest
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_projects_proto_depIdxs = []int32{
	0,  // 0: ng.v1.Project.status:type_name -> ng.v1.ProjectStatus
	0,  // 1: ng.v1.CreateProjectRequest.status:type_name -> ng.v1.ProjectStatus
	0,  // 2: ng.v1.ListProjectsRequest.status:type_name -> ng.v1.ProjectStatus
	1,  // 3: ng.v1.ListProjectsResponse.projects:type_name -> ng.v1.Project
	0,  // 4: ng.v1.UpdateProjectRequest.status:type_name -> ng.v1.ProjectStatus
	2,  // 5: ng.v1.ProjectService.Create:input_type -> ng.v1.CreateProjectRequest
	3,  // 6: ng.v1.ProjectService.Get:input_type -> ng.v1.GetProjectRequest
	4,  // 7: ng.v1.ProjectService.List:input_type -> ng.v1.ListProjectsRequest
	6,  // 8: ng.v1.ProjectService.Update:input_type -> ng.v1.UpdateProjectRequest
	7,  // 9: ng.v1.ProjectService.Delete:input_type -> ng.v1.DeleteProjectRequest
	1,  // 10: ng.v1.ProjectService.Create:output_type -> ng.v1.Project
	1,  // 11: ng.v1.ProjectService.Get:output_type -> ng.v1.Project
	5,  // 12: ng.v1.ProjectService.List:output_type -> ng.v1.ListProjectsResponse
	1,  // 13: ng.v1.ProjectService.Update:output_type -> ng.v1.Project
	8,  // 14: ng.v1.ProjectService.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_projects_proto_init() }
func file_projects_proto_init() {
	if File_projects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projects_proto_rawDesc), len(file_projects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projects_proto_goTypes,
		DependencyIndexes: file_projects_proto_depIdxs,
		EnumInfos:         file_projects_proto_enumTypes,
		MessageInfos:      file_projects_proto_msgTypes,
	}.Build()
	File_projects_proto = out.File
	file_projects_proto_goTypes = nil
	file_projects_proto_depIdxs = nil
}
