// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protograph/v1alpha1/options.proto

package protographv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParentRef declares that a field is a foreign-key reference to another proto
// message type. The protograph gateway uses this to automatically fan-out and
// stitch child entities onto parent responses.
//
// Fields 3-6 are optional overrides for when the default naming conventions
// ({TypeName}Service, "List", "Get") do not apply.
type ParentRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified parent message type, e.g. "ng.v1.Area". Required.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Filter field name in the child's List request, e.g. "area_id".
	// Defaults to the annotated field's own name when omitted.
	Via string `protobuf:"bytes,2,opt,name=via,proto3" json:"via,omitempty"`
	// Service to call when listing children.
	// Defaults to {pkg}.{ChildTypeName}Service when omitted.
	ListService string `protobuf:"bytes,3,opt,name=list_service,json=listService,proto3" json:"list_service,omitempty"`
	// Method to call when listing children.
	// Defaults to "List" when omitted.
	ListMethod string `protobuf:"bytes,4,opt,name=list_method,json=listMethod,proto3" json:"list_method,omitempty"`
	// Service to call when fetching the parent.
	// Defaults to {pkg}.{ParentTypeName}Service when omitted.
	GetService string `protobuf:"bytes,5,opt,name=get_service,json=getService,proto3" json:"get_service,omitempty"`
	// Method to call when fetching the parent.
	// Defaults to "Get" when omitted.
	GetMethod     string `protobuf:"bytes,6,opt,name=get_method,json=getMethod,proto3" json:"get_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentRef) Reset() {
	*x = ParentRef{}
	mi := &file_protograph_v1alpha1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentRef) ProtoMessage() {}

func (x *ParentRef) ProtoReflect() protoreflect.Message {
	mi := &file_protograph_v1alpha1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentRef.ProtoReflect.Descriptor instead.
func (*ParentRef) Descriptor() ([]byte, []int) {
	return file_protograph_v1alpha1_options_proto_rawDescGZIP(), []int{0}
}

func (x *ParentRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParentRef) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

func (x *ParentRef) GetListService() string {
	if x != nil {
		return x.ListService
	}
	return ""
}

func (x *ParentRef) GetListMethod() string {
	if x != nil {
		return x.ListMethod
	}
	return ""
}

func (x *ParentRef) GetGetService() string {
	if x != nil {
		return x.GetService
	}
	return ""
}

func (x *ParentRef) GetGetMethod() string {
	if x != nil {
		return x.GetMethod
	}
	return ""
}

var file_protograph_v1alpha1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ParentRef)(nil),
		Field:         50000,
		Name:          "protograph.v1alpha1.parent",
		Tag:           "bytes,50000,opt,name=parent",
		Filename:      "protograph/v1alpha1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protograph.v1alpha1.ParentRef parent = 50000;
	E_Parent = &file_protograph_v1alpha1_options_proto_extTypes[0]
)

var File_protograph_v1alpha1_options_proto protoreflect.FileDescriptor

const file_protograph_v1alpha1_options_proto_rawDesc = "" +
	"\n" +
	"!protograph/v1alpha1/options.proto\x12\x13protograph.v1alpha1\x1a google/protobuf/descriptor.proto\"\xb5\x01\n" +
	"\tParentRef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03via\x18\x02 \x01(\tR\x03via\x12!\n" +
	"\flist_service\x18\x03 \x01(\tR\vlistService\x12\x1f\n" +
	"\vlist_method\x18\x04 \x01(\tR\n" +
	"listMethod\x12\x1f\n" +
	"\vget_service\x18\x05 \x01(\tR\n" +
	"getService\x12\x1d\n" +
	"\n" +
	"get_method\x18\x06 \x01(\tR\tgetMethod:W\n" +
	"\x06parent\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\v2\x1e.protograph.v1alpha1.ParentRefR\x06parentBLZJgithub.com/liamawhite/ng/api/golang/protograph/v1alpha1;protographv1alpha1b\x06proto3"

var (
	file_protograph_v1alpha1_options_proto_rawDescOnce sync.Once
	file_protograph_v1alpha1_options_proto_rawDescData []byte
)

func file_protograph_v1alpha1_options_proto_rawDescGZIP() []byte {
	file_protograph_v1alpha1_options_proto_rawDescOnce.Do(func() {
		file_protograph_v1alpha1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protograph_v1alpha1_options_proto_rawDesc), len(file_protograph_v1alpha1_options_proto_rawDesc)))
	})
	return file_protograph_v1alpha1_options_proto_rawDescData
}

var file_protograph_v1alpha1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protograph_v1alpha1_options_proto_goTypes = []any{
	(*ParentRef)(nil),                 // 0: protograph.v1alpha1.ParentRef
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_protograph_v1alpha1_options_proto_depIdxs = []int32{
	1, // 0: protograph.v1alpha1.parent:extendee -> google.protobuf.FieldOptions
	0, // 1: protograph.v1alpha1.parent:type_name -> protograph.v1alpha1.ParentRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protograph_v1alpha1_options_proto_init() }
func file_protograph_v1alpha1_options_proto_init() {
	if File_protograph_v1alpha1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protograph_v1alpha1_options_proto_rawDesc), len(file_protograph_v1alpha1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protograph_v1alpha1_options_proto_goTypes,
		DependencyIndexes: file_protograph_v1alpha1_options_proto_depIdxs,
		MessageInfos:      file_protograph_v1alpha1_options_proto_msgTypes,
		ExtensionInfos:    file_protograph_v1alpha1_options_proto_extTypes,
	}.Build()
	File_protograph_v1alpha1_options_proto = out.File
	file_protograph_v1alpha1_options_proto_goTypes = nil
	file_protograph_v1alpha1_options_proto_depIdxs = nil
}
