// protograph-gen-ts is a protoc plugin that generates a typed TypeScript client
// for the protograph query gateway from .proto file descriptors.
//
// It reads a CodeGeneratorRequest from stdin, processes each requested .proto
// file, and writes a CodeGeneratorResponse to stdout.
//
// Generated output (one file per proto):
//   - <base>_protograph.ts  — typed query/result interfaces + createClient wrapper
package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const parentExtensionFieldNumber = 50000

func main() {
	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		die("read stdin: %v", err)
	}

	req := &pluginpb.CodeGeneratorRequest{}
	if err := proto.Unmarshal(data, req); err != nil {
		die("unmarshal request: %v", err)
	}

	resp := generate(req)

	out, err := proto.Marshal(resp)
	if err != nil {
		die("marshal response: %v", err)
	}
	if _, err := os.Stdout.Write(out); err != nil {
		die("write stdout: %v", err)
	}
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "protograph-gen-ts: "+format+"\n", args...)
	os.Exit(1)
}

// generate processes the CodeGeneratorRequest and returns the response.
func generate(req *pluginpb.CodeGeneratorRequest) *pluginpb.CodeGeneratorResponse {
	resp := &pluginpb.CodeGeneratorResponse{
		SupportedFeatures: proto.Uint64(uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)),
	}

	// Build a map of all file descriptors for lookups.
	allFiles := make(map[string]*descriptorpb.FileDescriptorProto, len(req.ProtoFile))
	for _, f := range req.ProtoFile {
		allFiles[f.GetName()] = f
	}

	// Only generate for the files listed in FileToGenerate.
	requested := make(map[string]bool, len(req.FileToGenerate))
	for _, name := range req.FileToGenerate {
		requested[name] = true
	}

	for _, f := range req.ProtoFile {
		if !requested[f.GetName()] {
			continue
		}
		content, err := generateFile(f, allFiles)
		if err != nil {
			errStr := err.Error()
			resp.Error = &errStr
			return resp
		}
		if content == "" {
			continue
		}
		outName := outputName(f.GetName())
		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    proto.String(outName),
			Content: proto.String(content),
		})
	}
	return resp
}

// outputName converts "path/to/foo.proto" → "path/to/foo_protograph.ts"
func outputName(protoName string) string {
	base := strings.TrimSuffix(protoName, ".proto")
	return base + "_protograph.ts"
}

// relationMeta holds the derived relation info for a parent→child relationship.
type relationMeta struct {
	ParentType   string
	FieldName    string
	ChildMsgName string // fully-qualified name of the child entity message
}

// generateFile generates the TypeScript content for a single proto file.
func generateFile(f *descriptorpb.FileDescriptorProto, allFiles map[string]*descriptorpb.FileDescriptorProto) (string, error) {
	pkg := f.GetPackage() // e.g. "ng.v1"

	if len(f.Service) == 0 {
		return "", nil
	}

	// Collect relations from (protograph.v1alpha1.edge) field annotations.
	// relations: targetType → fieldName → relationMeta
	relations := make(map[string]map[string]relationMeta)
	for _, msg := range f.MessageType {
		collectEdgeAnnotations(msg, pkg, relations)
	}

	var sb strings.Builder

	sb.WriteString("// Code generated by protograph-gen-ts. DO NOT EDIT.\n")
	sb.WriteString("// source: " + f.GetName() + "\n\n")
	sb.WriteString(`import { createClient as createGenericClient } from "../../protograph/ts/client.js";` + "\n\n")

	// Generate FieldSelection interfaces for all messages.
	for _, msg := range f.MessageType {
		writeFieldsInterface(&sb, msg, pkg, relations, allFiles, f)
	}

	// Generate Result interfaces for all messages.
	for _, msg := range f.MessageType {
		writeResultInterface(&sb, msg, pkg, relations, allFiles, f)
	}

	// Generate typed query interfaces for each service.
	for _, svc := range f.Service {
		writeServiceQueryInterface(&sb, svc, pkg, f, allFiles)
	}

	// Generate typed result type for each service.
	for _, svc := range f.Service {
		writeServiceResultType(&sb, svc, pkg)
	}

	// Generate a typed createClient wrapper.
	writeTypedCreateClient(&sb, f, pkg)

	return sb.String(), nil
}

// collectEdgeAnnotations walks message fields looking for (protograph.v1alpha1.edge)
// annotations and populates the relations map.
func collectEdgeAnnotations(msg *descriptorpb.DescriptorProto, pkg string, relations map[string]map[string]relationMeta) {
	msgFullName := pkg + "." + msg.GetName()
	for _, field := range msg.Field {
		ref := extractEdgeOption(field)
		if ref == nil {
			continue
		}
		fieldName := strings.ToLower(msg.GetName()) + "s" // e.g. "projects"
		if relations[ref.Type] == nil {
			relations[ref.Type] = make(map[string]relationMeta)
		}
		relations[ref.Type][fieldName] = relationMeta{
			ParentType:   ref.Type,
			FieldName:    fieldName,
			ChildMsgName: msgFullName,
		}
	}
	for _, nested := range msg.NestedType {
		collectEdgeAnnotations(nested, pkg+"."+msg.GetName(), relations)
	}
}

type edgeRefDecoded struct {
	Type        string // target message type, e.g. "ng.v1.Area"
	Via         string // filter field in ListRequest; empty = use FK field name
	ListService string // service for listing children; empty = {pkg}.{ChildType}Service
	ListMethod  string // method for listing children; empty = "List"
	GetService  string // service for getting target; empty = {pkg}.{TargetType}Service
	GetMethod   string // method for getting target; empty = "Get"
}

// extractEdgeOption reads the (protograph.v1alpha1.edge) EdgeRef message
// from FieldOptions raw bytes.
func extractEdgeOption(field *descriptorpb.FieldDescriptorProto) *edgeRefDecoded {
	opts := field.GetOptions()
	if opts == nil {
		return nil
	}
	raw := opts.ProtoReflect().GetUnknown()
	if len(raw) == 0 {
		return nil
	}
	// field 50000 is an EdgeRef message (wire type 2).
	data := extractFieldBytes(raw, parentExtensionFieldNumber)
	if len(data) == 0 {
		return nil
	}
	return decodeEdgeRef(data)
}

func decodeEdgeRef(b []byte) *edgeRefDecoded {
	out := &edgeRefDecoded{}
	i := 0
	for i < len(b) {
		tag, n := consumeVarint(b[i:])
		if n <= 0 {
			break
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7
		if wireType == 2 {
			length, n := consumeVarint(b[i:])
			if n <= 0 {
				break
			}
			i += n
			if int(length) > len(b)-i {
				break
			}
			s := string(b[i : i+int(length)])
			i += int(length)
			switch fieldNum {
			case 1:
				out.Type = s
			case 2:
				out.Via = s
			case 3:
				out.ListService = s
			case 4:
				out.ListMethod = s
			case 5:
				out.GetService = s
			case 6:
				out.GetMethod = s
			}
		} else {
			skipField(b, &i, wireType)
		}
	}
	if out.Type == "" {
		return nil
	}
	return out
}

// writeFieldsInterface emits a <MsgName>Fields interface.
func writeFieldsInterface(sb *strings.Builder, msg *descriptorpb.DescriptorProto, pkg string, relations map[string]map[string]relationMeta, allFiles map[string]*descriptorpb.FileDescriptorProto, f *descriptorpb.FileDescriptorProto) {
	msgFullName := pkg + "." + msg.GetName()
	sb.WriteString("export interface " + msg.GetName() + "Fields {\n")
	for _, field := range msg.Field {
		tsKey := camelCase(field.GetName())
		if field.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			childName := shortName(field.GetTypeName())
			sb.WriteString("  " + tsKey + "?: " + childName + "Fields;\n")
		} else {
			sb.WriteString("  " + tsKey + "?: Record<string, never>;\n")
		}
	}
	// Add relation fields.
	if rels, ok := relations[msgFullName]; ok {
		for fieldName, rel := range rels {
			childShort := shortName("." + rel.ChildMsgName)
			sb.WriteString("  " + fieldName + "?: " + childShort + "Fields;\n")
		}
	}
	sb.WriteString("}\n\n")

	for _, nested := range msg.NestedType {
		writeFieldsInterface(sb, nested, pkg+"."+msg.GetName(), relations, allFiles, f)
	}
}

// writeResultInterface emits a <MsgName>Result interface with TypeScript types.
func writeResultInterface(sb *strings.Builder, msg *descriptorpb.DescriptorProto, pkg string, relations map[string]map[string]relationMeta, allFiles map[string]*descriptorpb.FileDescriptorProto, f *descriptorpb.FileDescriptorProto) {
	msgFullName := pkg + "." + msg.GetName()
	sb.WriteString("export interface " + msg.GetName() + "Result {\n")
	for _, field := range msg.Field {
		tsKey := camelCase(field.GetName())
		tsType := protoTypeToTS(field)
		sb.WriteString("  " + tsKey + "?: " + tsType + ";\n")
	}
	// Add relation result fields.
	if rels, ok := relations[msgFullName]; ok {
		for fieldName, rel := range rels {
			childShort := shortName("." + rel.ChildMsgName)
			sb.WriteString("  " + fieldName + "?: " + childShort + "Result[];\n")
		}
	}
	sb.WriteString("}\n\n")

	for _, nested := range msg.NestedType {
		writeResultInterface(sb, nested, pkg+"."+msg.GetName(), relations, allFiles, f)
	}
}

// writeServiceQueryInterface emits a <ServiceName>Query type.
func writeServiceQueryInterface(sb *strings.Builder, svc *descriptorpb.ServiceDescriptorProto, pkg string, f *descriptorpb.FileDescriptorProto, allFiles map[string]*descriptorpb.FileDescriptorProto) {
	svcShort := svc.GetName()
	sb.WriteString("export type " + svcShort + "Query = {\n")
	for _, method := range svc.Method {
		respShort := shortName(method.GetOutputType())
		inputShort := shortName(method.GetInputType())
		sb.WriteString("  " + lcFirst(method.GetName()) + "?: {\n")
		sb.WriteString("    $?: Partial<" + inputShort + "Result>;\n")
		sb.WriteString("  } & " + respShort + "Fields;\n")
	}
	sb.WriteString("};\n\n")
}

// writeServiceResultType emits a <ServiceName>Result type.
func writeServiceResultType(sb *strings.Builder, svc *descriptorpb.ServiceDescriptorProto, pkg string) {
	svcShort := svc.GetName()
	sb.WriteString("export type " + svcShort + "Result = {\n")
	for _, method := range svc.Method {
		respShort := shortName(method.GetOutputType())
		sb.WriteString("  " + lcFirst(method.GetName()) + "?: " + respShort + "Result;\n")
	}
	sb.WriteString("};\n\n")
}

// writeTypedCreateClient emits a typed createClient wrapper.
func writeTypedCreateClient(sb *strings.Builder, f *descriptorpb.FileDescriptorProto, pkg string) {
	if len(f.Service) == 0 {
		return
	}

	sb.WriteString("export type TypedQuery = {\n")
	for _, svc := range f.Service {
		svcFull := pkg + "." + svc.GetName()
		sb.WriteString("  " + fmt.Sprintf("%q", svcFull) + "?: " + svc.GetName() + "Query;\n")
	}
	sb.WriteString("};\n\n")

	sb.WriteString("export type TypedResult = {\n")
	for _, svc := range f.Service {
		svcFull := pkg + "." + svc.GetName()
		sb.WriteString("  " + fmt.Sprintf("%q", svcFull) + "?: " + svc.GetName() + "Result;\n")
	}
	sb.WriteString("};\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * createClient returns a typed protograph client.\n")
	sb.WriteString(" * @param baseURL Base URL of the backend, e.g. \"http://localhost:8080\"\n")
	sb.WriteString(" */\n")
	sb.WriteString("export function createClient(baseURL: string) {\n")
	sb.WriteString("  const generic = createGenericClient(baseURL);\n")
	sb.WriteString("  return {\n")
	sb.WriteString("    async fetch(query: TypedQuery): Promise<TypedResult> {\n")
	sb.WriteString("      return generic.fetch(query as Record<string, unknown>) as Promise<TypedResult>;\n")
	sb.WriteString("    },\n")
	sb.WriteString("  };\n")
	sb.WriteString("}\n")
}

// --- Proto option decoding ---

// extractFieldBytes scans raw protobuf bytes and returns the value bytes of the
// first occurrence of the given field number (wire type 2 = length-delimited).
func extractFieldBytes(raw []byte, wantFieldNum uint64) []byte {
	b := raw
	for len(b) > 0 {
		tag, n := consumeVarint(b)
		if n <= 0 {
			break
		}
		b = b[n:]
		fieldNum := tag >> 3
		wireType := tag & 0x7
		if wireType == 2 {
			length, n := consumeVarint(b)
			if n <= 0 {
				break
			}
			b = b[n:]
			if int(length) > len(b) {
				break
			}
			data := b[:int(length)]
			b = b[int(length):]
			if fieldNum == wantFieldNum {
				return data
			}
		} else {
			// Skip other wire types.
			i := 0
			skipField(b, &i, wireType)
			b = b[i:]
		}
	}
	return nil
}

func consumeVarint(b []byte) (uint64, int) {
	var x uint64
	for s := uint(0); s < 64; s += 7 {
		if len(b) == 0 {
			return 0, -1
		}
		byt := b[0]
		b = b[1:]
		x |= uint64(byt&0x7f) << s
		if byt < 0x80 {
			return x, int(s/7) + 1
		}
	}
	return 0, -1
}

func skipField(b []byte, i *int, wireType uint64) {
	switch wireType {
	case 0:
		_, n := consumeVarint(b[*i:])
		if n > 0 {
			*i += n
		}
	case 1:
		*i += 8
	case 2:
		length, n := consumeVarint(b[*i:])
		if n > 0 {
			*i += n + int(length)
		}
	case 5:
		*i += 4
	}
}

// --- TypeScript type helpers ---

func protoTypeToTS(field *descriptorpb.FieldDescriptorProto) string {
	var baseType string
	switch field.GetType() {
	case descriptorpb.FieldDescriptorProto_TYPE_STRING:
		baseType = "string"
	case descriptorpb.FieldDescriptorProto_TYPE_BOOL:
		baseType = "boolean"
	case descriptorpb.FieldDescriptorProto_TYPE_INT32, descriptorpb.FieldDescriptorProto_TYPE_INT64,
		descriptorpb.FieldDescriptorProto_TYPE_UINT32, descriptorpb.FieldDescriptorProto_TYPE_UINT64,
		descriptorpb.FieldDescriptorProto_TYPE_SINT32, descriptorpb.FieldDescriptorProto_TYPE_SINT64,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED32, descriptorpb.FieldDescriptorProto_TYPE_FIXED64,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED32, descriptorpb.FieldDescriptorProto_TYPE_SFIXED64,
		descriptorpb.FieldDescriptorProto_TYPE_FLOAT, descriptorpb.FieldDescriptorProto_TYPE_DOUBLE:
		baseType = "number"
	case descriptorpb.FieldDescriptorProto_TYPE_BYTES:
		baseType = "string" // base64 in protojson
	case descriptorpb.FieldDescriptorProto_TYPE_ENUM:
		baseType = "number"
	case descriptorpb.FieldDescriptorProto_TYPE_MESSAGE:
		baseType = shortName(field.GetTypeName()) + "Result"
	default:
		baseType = "unknown"
	}

	isRepeated := field.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED
	if isRepeated {
		return baseType + "[]"
	}
	return baseType
}

// shortName extracts the last component of a fully-qualified proto type name.
// ".ng.v1.Area" → "Area"
func shortName(fullName string) string {
	parts := strings.Split(strings.TrimPrefix(fullName, "."), ".")
	return parts[len(parts)-1]
}

// camelCase converts proto_snake to lowerCamelCase.
func camelCase(s string) string {
	parts := strings.Split(s, "_")
	if len(parts) == 1 {
		return s
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(p)
			continue
		}
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
