// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file protograph/v1alpha1/options.proto (package protograph.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protograph/v1alpha1/options.proto.
 */
export const file_protograph_v1alpha1_options: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90b2dyYXBoL3YxYWxwaGExL29wdGlvbnMucHJvdG8SE3Byb3RvZ3JhcGgudjFhbHBoYTEiegoJUGFyZW50UmVmEgwKBHR5cGUYASABKAkSCwoDdmlhGAIgASgJEhQKDGxpc3Rfc2VydmljZRgDIAEoCRITCgtsaXN0X21ldGhvZBgEIAEoCRITCgtnZXRfc2VydmljZRgFIAEoCRISCgpnZXRfbWV0aG9kGAYgASgJOlcKBnBhcmVudBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY0IYDIAEoCzIeLnByb3RvZ3JhcGgudjFhbHBoYTEuUGFyZW50UmVmUgZwYXJlbnRCTFpKZ2l0aHViLmNvbS9saWFtYXdoaXRlL25nL2FwaS9nb2xhbmcvcHJvdG9ncmFwaC92MWFscGhhMTtwcm90b2dyYXBodjFhbHBoYTFiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * ParentRef declares that a field is a foreign-key reference to another proto
 * message type. The protograph gateway uses this to automatically fan-out and
 * stitch child entities onto parent responses.
 *
 * Fields 3-6 are optional overrides for when the default naming conventions
 * ({TypeName}Service, "List", "Get") do not apply.
 *
 * @generated from message protograph.v1alpha1.ParentRef
 */
export type ParentRef = Message<"protograph.v1alpha1.ParentRef"> & {
  /**
   * Fully-qualified parent message type, e.g. "ng.v1.Area". Required.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Filter field name in the child's List request, e.g. "area_id".
   * Defaults to the annotated field's own name when omitted.
   *
   * @generated from field: string via = 2;
   */
  via: string;

  /**
   * Service to call when listing children.
   * Defaults to {pkg}.{ChildTypeName}Service when omitted.
   *
   * @generated from field: string list_service = 3;
   */
  listService: string;

  /**
   * Method to call when listing children.
   * Defaults to "List" when omitted.
   *
   * @generated from field: string list_method = 4;
   */
  listMethod: string;

  /**
   * Service to call when fetching the parent.
   * Defaults to {pkg}.{ParentTypeName}Service when omitted.
   *
   * @generated from field: string get_service = 5;
   */
  getService: string;

  /**
   * Method to call when fetching the parent.
   * Defaults to "Get" when omitted.
   *
   * @generated from field: string get_method = 6;
   */
  getMethod: string;
};

/**
 * Describes the message protograph.v1alpha1.ParentRef.
 * Use `create(ParentRefSchema)` to create a new message.
 */
export const ParentRefSchema: GenMessage<ParentRef> = /*@__PURE__*/
  messageDesc(file_protograph_v1alpha1_options, 0);

/**
 * @generated from extension: protograph.v1alpha1.ParentRef parent = 50000;
 */
export const parent: GenExtension<FieldOptions, ParentRef> = /*@__PURE__*/
  extDesc(file_protograph_v1alpha1_options, 0);

