// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file protograph/v1alpha1/options.proto (package protograph.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protograph/v1alpha1/options.proto.
 */
export const file_protograph_v1alpha1_options: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90b2dyYXBoL3YxYWxwaGExL29wdGlvbnMucHJvdG8SE3Byb3RvZ3JhcGgudjFhbHBoYTEieAoHRWRnZVJlZhIMCgR0eXBlGAEgASgJEgsKA3ZpYRgCIAEoCRIUCgxsaXN0X3NlcnZpY2UYAyABKAkSEwoLbGlzdF9tZXRob2QYBCABKAkSEwoLZ2V0X3NlcnZpY2UYBSABKAkSEgoKZ2V0X21ldGhvZBgGIAEoCTpRCgRlZGdlEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjQhgMgASgLMhwucHJvdG9ncmFwaC52MWFscGhhMS5FZGdlUmVmUgRlZGdlQkxaSmdpdGh1Yi5jb20vbGlhbWF3aGl0ZS9uZy9hcGkvZ29sYW5nL3Byb3RvZ3JhcGgvdjFhbHBoYTE7cHJvdG9ncmFwaHYxYWxwaGExYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * EdgeRef declares that a field is a foreign-key reference to another proto
 * message type. The protograph gateway uses this to automatically fan-out and
 * stitch related entities onto responses.
 *
 * Fields 3-6 are optional overrides for when the default naming conventions
 * ({TypeName}Service, "List", "Get") do not apply.
 *
 * @generated from message protograph.v1alpha1.EdgeRef
 */
export type EdgeRef = Message<"protograph.v1alpha1.EdgeRef"> & {
  /**
   * Fully-qualified target message type, e.g. "ng.v1.Area". Required.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Filter field name in the target's List request, e.g. "area_id".
   * Defaults to the annotated field's own name when omitted.
   *
   * @generated from field: string via = 2;
   */
  via: string;

  /**
   * Service to call when listing related entities.
   * Defaults to {pkg}.{ChildTypeName}Service when omitted.
   *
   * @generated from field: string list_service = 3;
   */
  listService: string;

  /**
   * Method to call when listing related entities.
   * Defaults to "List" when omitted.
   *
   * @generated from field: string list_method = 4;
   */
  listMethod: string;

  /**
   * Service to call when fetching the target.
   * Defaults to {pkg}.{TargetTypeName}Service when omitted.
   *
   * @generated from field: string get_service = 5;
   */
  getService: string;

  /**
   * Method to call when fetching the target.
   * Defaults to "Get" when omitted.
   *
   * @generated from field: string get_method = 6;
   */
  getMethod: string;
};

/**
 * Describes the message protograph.v1alpha1.EdgeRef.
 * Use `create(EdgeRefSchema)` to create a new message.
 */
export const EdgeRefSchema: GenMessage<EdgeRef> = /*@__PURE__*/
  messageDesc(file_protograph_v1alpha1_options, 0);

/**
 * @generated from extension: protograph.v1alpha1.EdgeRef edge = 50000;
 */
export const edge: GenExtension<FieldOptions, EdgeRef> = /*@__PURE__*/
  extDesc(file_protograph_v1alpha1_options, 0);

